// Generated static word banks. The live game does not call external APIs.
window.CHARADES_CATEGORIES = {
  "Animals": [
    "Elephant",
    "Penguin",
    "Giraffe",
    "Kangaroo",
    "Dolphin",
    "Octopus",
    "Crocodile",
    "Flamingo",
    "Gorilla",
    "Butterfly",
    "Shark",
    "Tiger",
    "Lion",
    "Monkey",
    "Rabbit",
    "Turtle",
    "Snake",
    "Horse",
    "Zebra",
    "Owl",
    "Panda",
    "Koala",
    "Wolf",
    "Fox",
    "Bear",
    "Eagle",
    "Peacock",
    "Camel",
    "Hippo",
    "Rhino",
    "Aardvark",
    "Abyssinian",
    "Adelie Penguin",
    "Affenpinscher",
    "Afghan Hound",
    "African Bush Elephant",
    "African Civet",
    "African Clawed Frog",
    "African Forest Elephant",
    "African Palm Civet",
    "African Penguin",
    "African Tree Toad",
    "African Wild Dog",
    "Ainu Dog",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alaskan Malamute",
    "Albatross",
    "Aldabra Giant Tortoise",
    "Alligator",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd Dog",
    "Angelfish",
    "Ant",
    "Anteater",
    "Antelope",
    "Appenzeller Dog",
    "Arctic Fox",
    "Arctic Hare",
    "Arctic Wolf",
    "Armadillo",
    "Asian Elephant",
    "Asian Giant Hornet",
    "Asian Palm Civet",
    "Asiatic Black Bear",
    "Australian Cattle Dog",
    "Australian Kelpie Dog",
    "Australian Mist",
    "Australian Shepherd",
    "Australian Terrier",
    "Avocet",
    "Axolotl",
    "Aye Aye",
    "Baboon",
    "Bactrian Camel",
    "Badger",
    "Balinese",
    "Banded Palm Civet",
    "Bandicoot",
    "Barb",
    "Barn Owl",
    "Barnacle",
    "Barracuda",
    "Basenji Dog",
    "Basking Shark",
    "Basset Hound",
    "Bat",
    "Bavarian Mountain Hound",
    "Beagle",
    "Bearded Collie",
    "Bearded Dragon",
    "Beaver",
    "Bedlington Terrier",
    "Beetle",
    "Bengal Tiger",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Binturong",
    "Bird",
    "Birds Of Paradise",
    "Birman",
    "Bison",
    "Black Bear",
    "Black Rhinoceros",
    "Black Russian Terrier",
    "Black Widow Spider",
    "Bloodhound",
    "Blue Lacy Dog",
    "Blue Whale",
    "Bluetick Coonhound",
    "Bobcat",
    "Bolognese Dog",
    "Bombay",
    "Bongo",
    "Bonobo",
    "Booby",
    "Border Collie",
    "Border Terrier",
    "Bornean Orang-utan",
    "Borneo Elephant",
    "Boston Terrier",
    "Bottle Nosed Dolphin",
    "Boxer Dog",
    "Boykin Spaniel",
    "Brazilian Terrier",
    "Brown Bear",
    "Budgerigar",
    "Buffalo",
    "Bull Mastiff",
    "Bull Shark",
    "Bull Terrier",
    "Bulldog",
    "Bullfrog",
    "Bumble Bee",
    "Burmese",
    "Burrowing Frog",
    "Butterfly Fish",
    "Caiman",
    "Caiman Lizard",
    "Cairn Terrier",
    "Canaan Dog",
    "Capybara",
    "Caracal",
    "Carolina Dog",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Catfish",
    "Cavalier King Charles Spaniel",
    "Centipede",
    "Cesky Fousek",
    "Chameleon",
    "Chamois",
    "Cheetah",
    "Chesapeake Bay Retriever",
    "Chicken",
    "Chihuahua",
    "Chimpanzee",
    "Chinchilla",
    "Chinese Crested Dog",
    "Chinook",
    "Chinstrap Penguin",
    "Chipmunk",
    "Chow Chow",
    "Cichlid",
    "Clouded Leopard",
    "Clown Fish",
    "Clumber Spaniel",
    "Coati",
    "Cockroach",
    "Collared Peccary",
    "Collie",
    "Common Buzzard",
    "Common Frog",
    "Common Loon",
    "Common Toad",
    "Coral",
    "Cottontop Tamarin",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crab-Eating Macaque",
    "Crane",
    "Crested Penguin",
    "Cross River Gorilla",
    "Curly Coated Retriever",
    "Cuscus",
    "Cuttlefish",
    "Dachshund",
    "Dalmatian",
    "Darwin's Frog",
    "Deer",
    "Desert Tortoise",
    "Deutsche Bracke",
    "Dhole",
    "Dingo",
    "Discus",
    "Doberman Pinscher",
    "Dodo",
    "Dog",
    "Dogo Argentino",
    "Dogue De Bordeaux",
    "Donkey",
    "Dormouse",
    "Dragonfly",
    "Drever",
    "Duck",
    "Dugong",
    "Dunker",
    "Dusky Dolphin",
    "Dwarf Crocodile",
    "Earwig",
    "Eastern Gorilla",
    "Eastern Lowland Gorilla",
    "Echidna",
    "Edible Frog",
    "Egyptian Mau",
    "Electric Eel",
    "Elephant Seal",
    "Elephant Shrew",
    "Emperor Penguin",
    "Emperor Tamarin",
    "Emu",
    "English Cocker Spaniel",
    "English Shepherd",
    "English Springer Spaniel",
    "Entlebucher Mountain Dog",
    "Epagneul Pont Audemer",
    "Eskimo Dog",
    "Estrela Mountain Dog",
    "Falcon",
    "Fennec Fox",
    "Ferret",
    "Field Spaniel",
    "Fin Whale",
    "Finnish Spitz",
    "Fire-Bellied Toad",
    "Fish",
    "Fishing Cat",
    "Flat Coat Retriever",
    "Flounder",
    "Fly",
    "Flying Squirrel",
    "Fossa",
    "Fox Terrier",
    "French Bulldog",
    "Frigatebird",
    "Frilled Lizard",
    "Frog",
    "Fur Seal",
    "Galapagos Penguin",
    "Galapagos Tortoise",
    "Gar",
    "Gecko",
    "Gentoo Penguin",
    "Geoffroys Tamarin",
    "Gerbil",
    "German Pinscher",
    "German Shepherd",
    "Gharial",
    "Giant African Land Snail",
    "Giant Clam",
    "Giant Panda Bear",
    "Giant Schnauzer",
    "Gibbon",
    "Gila Monster",
    "Glass Lizard",
    "Glow Worm",
    "Goat",
    "Golden Lion Tamarin",
    "Golden Oriole",
    "Golden Retriever",
    "Goose",
    "Gopher",
    "Grasshopper",
    "Great Dane",
    "Great White Shark",
    "Greater Swiss Mountain Dog",
    "Green Bee-Eater",
    "Greenland Dog",
    "Grey Mouse Lemur",
    "Grey Reef Shark",
    "Grey Seal",
    "Greyhound",
    "Grizzly Bear",
    "Grouse",
    "Guinea Fowl",
    "Guinea Pig",
    "Guppy",
    "Hammerhead Shark",
    "Hamster",
    "Hare",
    "Harrier",
    "Havanese",
    "Hedgehog",
    "Hercules Beetle",
    "Hermit Crab",
    "Heron",
    "Highland Cattle",
    "Himalayan",
    "Hippopotamus",
    "Honey Bee",
    "Horn Shark",
    "Horned Frog",
    "Horseshoe Crab",
    "Howler Monkey",
    "Human",
    "Humboldt Penguin",
    "Hummingbird",
    "Humpback Whale",
    "Hyena",
    "Ibis",
    "Ibizan Hound",
    "Iguana",
    "Impala",
    "Indian Elephant",
    "Indian Palm Squirrel",
    "Indian Rhinoceros",
    "Indian Star Tortoise",
    "Indochinese Tiger",
    "Indri",
    "Insect",
    "Irish Setter",
    "Irish WolfHound",
    "Jack Russel",
    "Jackal",
    "Jaguar",
    "Japanese Chin",
    "Japanese Macaque",
    "Javan Rhinoceros",
    "Javanese",
    "Jellyfish",
    "Kakapo",
    "Keel Billed Toucan",
    "Killer Whale",
    "King Crab",
    "King Penguin",
    "Kingfisher",
    "Kiwi",
    "Komodo Dragon",
    "Kudu",
    "Labradoodle",
    "Labrador Retriever",
    "Ladybird",
    "Leaf-Tailed Gecko",
    "Lemming",
    "Lemur",
    "Leopard",
    "Leopard Cat",
    "Leopard Seal",
    "Leopard Tortoise",
    "Liger",
    "Lionfish",
    "Little Penguin",
    "Lizard",
    "Llama",
    "Lobster",
    "Long-Eared Owl",
    "Lynx",
    "Macaroni Penguin",
    "Macaw",
    "Magellanic Penguin",
    "Magpie",
    "Maine Coon",
    "Malayan Civet",
    "Malayan Tiger",
    "Maltese",
    "Manatee",
    "Mandrill",
    "Manta Ray",
    "Marine Toad",
    "Markhor",
    "Marsh Frog",
    "Masked Palm Civet",
    "Mastiff",
    "Mayfly",
    "Meerkat",
    "Millipede",
    "Minke Whale",
    "Mole",
    "Molly",
    "Mongoose",
    "Mongrel",
    "Monitor Lizard",
    "Monte Iberia Eleuth",
    "Moorhen",
    "Moose",
    "Moray Eel",
    "Moth",
    "Mountain Gorilla",
    "Mountain Lion",
    "Mouse",
    "Mule",
    "Neanderthal",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Newt",
    "Nightingale",
    "Norfolk Terrier",
    "Norwegian Forest",
    "Numbat",
    "Nurse Shark",
    "Ocelot",
    "Okapi",
    "Old English Sheepdog",
    "Olm",
    "Opossum",
    "Orang-utan",
    "Ostrich",
    "Otter",
    "Oyster",
    "Pademelon",
    "Panther",
    "Parrot",
    "Patas Monkey",
    "Pekingese",
    "Pelican",
    "Persian",
    "Pheasant",
    "Pied Tamarin",
    "Pig",
    "Pika",
    "Pike",
    "Pink Fairy Armadillo",
    "Piranha",
    "Platypus",
    "Pointer",
    "Poison Dart Frog",
    "Polar Bear",
    "Pond Skater",
    "Poodle",
    "Pool Frog",
    "Porcupine",
    "Possum",
    "Prawn",
    "Proboscis Monkey",
    "Puffer Fish",
    "Puffin",
    "Pug",
    "Puma",
    "Purple Emperor",
    "Puss Moth",
    "Pygmy Hippopotamus",
    "Pygmy Marmoset",
    "Quail",
    "Quetzal",
    "Quokka",
    "Quoll",
    "Raccoon",
    "Raccoon Dog",
    "Radiated Tortoise",
    "Ragdoll",
    "Rat",
    "Rattlesnake",
    "Red Knee Tarantula",
    "Red Panda",
    "Red Wolf",
    "Red-handed Tamarin",
    "Reindeer",
    "Rhinoceros",
    "River Dolphin",
    "River Turtle",
    "Robin",
    "Rock Hyrax",
    "Rockhopper Penguin",
    "Roseate Spoonbill",
    "Rottweiler",
    "Royal Penguin",
    "Russian Blue",
    "Sabre-Toothed Tiger",
    "Saint Bernard",
    "Salamander",
    "Sand Lizard",
    "Saola",
    "Scorpion",
    "Scorpion Fish",
    "Sea Dragon",
    "Sea Lion",
    "Sea Otter",
    "Sea Slug",
    "Sea Squirt",
    "Sea Turtle",
    "Sea Urchin",
    "Seahorse",
    "Seal",
    "Serval",
    "Sheep",
    "Shih Tzu",
    "Shrimp",
    "Siamese"
  ],
  "Movies": [
    "Titanic",
    "Avatar",
    "Frozen",
    "Shrek",
    "Jaws",
    "The Avengers",
    "Jurassic Park",
    "Toy Story",
    "The Lion King",
    "Finding Nemo",
    "Spider-Man",
    "Iron Man",
    "Black Panther",
    "The Dark Knight",
    "Home Alone",
    "Harry Potter",
    "The Hunger Games",
    "Star Wars",
    "The Matrix",
    "Ghostbusters",
    "Barbie",
    "Oppenheimer",
    "The Incredibles",
    "Moana",
    "Aladdin",
    "Cars",
    "Ratatouille",
    "The Notebook",
    "Mean Girls",
    "Interstellar",
    "Minions",
    "Guardians of the Galaxy",
    "Mad Max: Fury Road",
    "Jurassic World",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Dawn of the Planet of the Apes",
    "The Hunger Games: Mockingjay - Part 1",
    "Big Hero 6",
    "Terminator Genisys",
    "Captain America: Civil War",
    "The Martian",
    "Inception",
    "Batman v Superman: Dawn of Justice",
    "Fight Club",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Teenage Mutant Ninja Turtles",
    "Gone Girl",
    "Pixels",
    "Fury",
    "X-Men: Apocalypse",
    "Pirates of the Caribbean: At World's End",
    "Rise of the Planet of the Apes",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Despicable Me 2",
    "Pirates of the Caribbean: On Stranger Tides",
    "Avengers: Age of Ultron",
    "Harry Potter and the Chamber of Secrets",
    "Tomorrowland",
    "Inside Out",
    "The Hunger Games: Mockingjay - Part 2",
    "Brave",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: The Battle of the Five Armies",
    "Ant-Man",
    "X-Men: Days of Future Past",
    "Transformers: Age of Extinction",
    "Spider-Man 3",
    "Night at the Museum: Secret of the Tomb",
    "Batman Begins",
    "Mission: Impossible - Rogue Nation",
    "Despicable Me",
    "Maze Runner: The Scorch Trials",
    "The Dark Knight Rises",
    "Maleficent",
    "Gravity",
    "Harry Potter and the Philosopher's Stone",
    "Bruce Almighty",
    "The Fifth Element",
    "The Hobbit: An Unexpected Journey",
    "Quantum of Solace",
    "Spectre",
    "The Twilight Saga: Eclipse",
    "The Lord of the Rings: The Two Towers",
    "Monsters, Inc.",
    "Men in Black",
    "Insurgent",
    "The Green Mile",
    "Furious 7",
    "Terminator 2: Judgment Day",
    "Exodus: Gods and Kings",
    "Harry Potter and the Goblet of Fire",
    "Cinderella",
    "The Revenant",
    "San Andreas",
    "How to Train Your Dragon 2",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "Ice Age",
    "Thor: The Dark World",
    "Man of Steel",
    "Harry Potter and the Half-Blood Prince",
    "I, Robot",
    "Gladiator",
    "The Wolf of Wall Street",
    "The Hobbit: The Desolation of Smaug",
    "The Jungle Book",
    "Skyfall",
    "Up",
    "Men in Black II",
    "The Bourne Legacy",
    "Suicide Squad",
    "The Adventures of Tintin",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Monsters University",
    "Casino Royale",
    "Thor",
    "The Bourne Identity",
    "Allegiant",
    "Sin City: A Dame to Kill For",
    "Jupiter Ascending",
    "Ice Age: The Meltdown",
    "Kung Fu Panda",
    "Penguins of Madagascar",
    "Django Unchained",
    "Shutter Island",
    "World War Z",
    "Night at the Museum: Battle of the Smithsonian",
    "Sherlock Holmes: A Game of Shadows",
    "Divergent",
    "Harry Potter and the Prisoner of Azkaban",
    "Edge of Tomorrow",
    "Alice in Wonderland",
    "Star Trek Into Darkness",
    "Harry Potter and the Order of the Phoenix",
    "Mission: Impossible - Ghost Protocol",
    "Iron Man 3",
    "The Expendables",
    "Iron Man 2",
    "Snow White and the Huntsman",
    "Hercules",
    "Ocean's Twelve",
    "The Hunger Games: Catching Fire",
    "Saving Private Ryan",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Mission: Impossible",
    "Captain America: The First Avenger",
    "Cloud Atlas",
    "Wanted",
    "TRON: Legacy",
    "Star Trek",
    "Toy Story 2",
    "The Matrix Revolutions",
    "Inglourious Basterds",
    "Captain America: The Winter Soldier",
    "Terminator Salvation",
    "300: Rise of an Empire",
    "Now You See Me",
    "I Am Legend",
    "The Matrix Reloaded",
    "Ice Age: Dawn of the Dinosaurs",
    "Terminator 3: Rise of the Machines",
    "Prometheus",
    "Megamind",
    "Ted 2",
    "The Hateful Eight",
    "Apollo 13",
    "Oblivion",
    "Angels & Demons",
    "Mulan",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Elysium",
    "How to Train Your Dragon",
    "Troy",
    "RoboCop",
    "WALL·E",
    "Minority Report",
    "A Good Day to Die Hard",
    "Star Trek Beyond",
    "Ice Age: Continental Drift",
    "Battleship",
    "Watchmen",
    "Dracula Untold",
    "The Croods",
    "Seventh Son",
    "Home",
    "The Departed",
    "Warcraft",
    "Mission: Impossible III",
    "The Incredible Hulk",
    "The Italian Job",
    "Jason Bourne",
    "The Princess and the Frog",
    "Wreck-It Ralph",
    "Prince of Persia: The Sands of Time",
    "Rise of the Guardians",
    "Hotel Transylvania 2",
    "50 First Dates",
    "King Kong",
    "The Great Gatsby",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "The Expendables 3",
    "Ocean's Eleven",
    "Fantastic 4: Rise of the Silver Surfer",
    "Braveheart",
    "The Huntsman: Winter's War",
    "Independence Day",
    "The Curious Case of Benjamin Button",
    "Everest",
    "The Mummy: Tomb of the Dragon Emperor",
    "Toy Story 3",
    "GoldenEye",
    "Focus",
    "Olympus Has Fallen",
    "G.I. Joe: Retaliation",
    "A Beautiful Mind",
    "Batman Returns",
    "Transcendence",
    "National Treasure",
    "Starship Troopers",
    "Hellboy II: The Golden Army",
    "Armageddon",
    "Underworld: Awakening",
    "The Hangover Part II",
    "Superman Returns",
    "Sherlock Holmes",
    "The Terminal",
    "Cast Away",
    "Die Hard 2",
    "Dredd",
    "Lara Croft Tomb Raider: The Cradle of Life",
    "Hancock",
    "Kung Fu Panda 3",
    "Pacific Rim",
    "The Truman Show",
    "Alice Through the Looking Glass",
    "Hotel Transylvania",
    "Gods of Egypt",
    "Lilo & Stitch",
    "Contact",
    "Mission: Impossible II",
    "Need for Speed",
    "Die Another Day",
    "Star Wars: Episode I - The Phantom Menace",
    "The Chronicles of Narnia: Prince Caspian",
    "Charlie and the Chocolate Factory",
    "The Expendables 2",
    "The Bourne Supremacy",
    "Gone in Sixty Seconds",
    "Blood Diamond",
    "The Last Witch Hunter",
    "The Last Samurai",
    "Men in Black 3",
    "Zodiac",
    "Die Hard: With a Vengeance",
    "Green Lantern",
    "The Good Dinosaur",
    "Atlantis: The Lost Empire",
    "Now You See Me 2",
    "The Rock",
    "Life of Pi",
    "Kung Fu Panda 2",
    "Planet of the Apes",
    "The Emperor's New Groove",
    "In the Heart of the Sea",
    "Pompeii",
    "Dark Shadows",
    "Batman & Robin",
    "Cars 2",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Blade: Trinity",
    "Battle: Los Angeles",
    "Road to Perdition",
    "The Lone Ranger",
    "Live Free or Die Hard",
    "Salt",
    "Night at the Museum",
    "Independence Day: Resurgence",
    "The Man from U.N.C.L.E.",
    "Tangled",
    "War of the Worlds",
    "Les Misérables",
    "Batman Forever",
    "Mirror Mirror",
    "Madagascar",
    "Pan",
    "Stardust",
    "Chicken Little",
    "Clash of the Titans",
    "The Girl with the Dragon Tattoo",
    "The League of Extraordinary Gentlemen",
    "The Polar Express",
    "Shrek 2",
    "Shark Tale",
    "Oz: The Great and Powerful",
    "Eagle Eye",
    "The Simpsons Movie",
    "Ghost Rider",
    "Blackhat",
    "Cloudy with a Chance of Meatballs",
    "The Hunchback of Notre Dame",
    "xXx",
    "Rio",
    "Big Fish",
    "Gangs of New York",
    "Noah",
    "Face/Off",
    "Ender's Game",
    "The Angry Birds Movie",
    "The Aviator",
    "Grown Ups 2",
    "How the Grinch Stole Christmas",
    "The Bourne Ultimatum",
    "The Da Vinci Code",
    "Con Air",
    "Madagascar 3: Europe's Most Wanted",
    "The Holiday",
    "Wrath of the Titans",
    "Knight and Day",
    "Turbo",
    "Waterworld",
    "Mr. & Mrs. Smith",
    "Kingdom of Heaven",
    "Escape Plan",
    "Black Hawk Down",
    "RED 2",
    "The BFG",
    "Madagascar: Escape 2 Africa",
    "Star Wars: Episode III - Revenge of the Sith",
    "Mars Attacks!",
    "Shrek Forever After",
    "Star Wars: Episode II - Attack of the Clones",
    "John Carter",
    "The Monuments Men",
    "Due Date",
    "Jack the Giant Slayer",
    "The Secret Life of Walter Mitty",
    "Tropic Thunder",
    "Total Recall",
    "Unbroken",
    "The Golden Compass",
    "Shrek the Third",
    "AVP: Alien vs. Predator",
    "Tomorrow Never Dies",
    "2 Guns",
    "After Earth",
    "The Legend of Tarzan",
    "Death Race",
    "Perfume: The Story of a Murderer",
    "Rio 2",
    "American Gangster",
    "Ocean's Thirteen",
    "Unbreakable",
    "The Day the Earth Stood Still",
    "The Mummy Returns",
    "Bolt",
    "47 Ronin",
    "Spirit: Stallion of the Cimarron",
    "Antz",
    "Lara Croft: Tomb Raider",
    "The Tourist",
    "The Day After Tomorrow",
    "Enemy at the Gates",
    "Cloudy with a Chance of Meatballs 2",
    "Enemy of the State",
    "Click",
    "Wild Wild West",
    "Journey 2: The Mysterious Island",
    "The Taking of Pelham 1 2 3",
    "You Don't Mess with the Zohan",
    "Percy Jackson: Sea of Monsters",
    "Charlie's Angels",
    "The Brothers Grimm",
    "Austin Powers in Goldmember",
    "Teenage Mutant Ninja Turtles: Out of the Shadows",
    "A Christmas Carol",
    "The World Is Not Enough",
    "R.I.P.D.",
    "Sucker Punch",
    "Alexander",
    "White House Down",
    "This Means War",
    "Treasure Planet",
    "Scott Pilgrim vs. the World",
    "Grown Ups",
    "Valkyrie",
    "Mr. Peabody & Sherman",
    "True Lies",
    "Abraham Lincoln: Vampire Hunter",
    "Fantastic Four",
    "Bad Boys II",
    "Immortals",
    "Unstoppable",
    "The Island",
    "Robin Hood",
    "Body of Lies",
    "Legend of the Guardians: The Owls of Ga'Hoole",
    "Happy Feet",
    "Real Steel",
    "The Road to El Dorado",
    "Just Go with It",
    "Master and Commander: The Far Side of the World",
    "The SpongeBob Movie: Sponge Out of Water",
    "Swordfish",
    "Tower Heist",
    "Epic",
    "Surrogates",
    "The Smurfs",
    "The Three Musketeers",
    "Air Force One",
    "Monster House",
    "Over the Hedge",
    "Lincoln",
    "Monsters vs Aliens",
    "Space Jam",
    "Meet Joe Black",
    "Rush Hour 2",
    "Beowulf",
    "The Sorcerer's Apprentice",
    "Children of Men",
    "The Little Prince",
    "Spider-Man 2",
    "Hulk",
    "Safe House",
    "The Peanuts Movie",
    "Pearl Harbor",
    "Deep Impact",
    "S.W.A.T.",
    "A.I. Artificial Intelligence",
    "The Last Airbender",
    "Public Enemies",
    "Hook",
    "Charlie's Angels: Full Throttle",
    "Point Break",
    "Annie",
    "G.I. Joe: The Rise of Cobra",
    "Meet the Fockers",
    "The Smurfs 2",
    "Little Fockers",
    "The Book of Eli",
    "Hugo",
    "Catwoman",
    "Jarhead",
    "Twister",
    "Last Action Hero",
    "Conan the Barbarian",
    "Wild Hogs",
    "The Green Hornet",
    "Where the Wild Things Are",
    "The Secret Life of Pets",
    "Scooby-Doo",
    "What Women Want",
    "The Dictator",
    "I, Frankenstein",
    "Hairspray",
    "The Mask of Zorro",
    "The Legend of Zorro",
    "Marley & Me",
    "Eragon",
    "Stuart Little",
    "Green Zone",
    "Rango",
    "Ben-Hur",
    "Robots",
    "War Horse",
    "Killer Elite",
    "The Prince of Egypt",
    "Alvin and the Chipmunks: The Squeakquel",
    "Bee Movie",
    "Doom",
    "The Lovely Bones",
    "Enchanted",
    "The Core",
    "Munich",
    "Signs",
    "Australia",
    "Eat Pray Love",
    "Elektra",
    "You've Got Mail",
    "Transformers: Dark of the Moon",
    "The Finest Hours",
    "Hollow Man",
    "Stuart Little 2",
    "Eyes Wide Shut",
    "Alvin and the Chipmunks: The Road Chip",
    "The Chronicles of Riddick",
    "The Village",
    "Zookeeper",
    "Vanilla Sky",
    "The 13th Warrior",
    "Spy Game",
    "Hall Pass",
    "Arthur and the Invisibles",
    "Evan Almighty",
    "Tears of the Sun",
    "Dreamcatcher",
    "G-Force",
    "Couples Retreat",
    "Open Season",
    "Dinosaur",
    "Cliffhanger"
  ],
  "Video Games": [
    "Minecraft",
    "Fortnite",
    "Roblox",
    "Grand Theft Auto V",
    "Call of Duty",
    "Call of Duty: Warzone",
    "Mario Kart",
    "Super Mario Bros.",
    "Pokémon",
    "Pokémon GO",
    "The Legend of Zelda",
    "The Legend of Zelda: Breath of the Wild",
    "Animal Crossing",
    "Wii Sports",
    "Super Smash Bros.",
    "Mario Party",
    "Among Us",
    "Fall Guys",
    "Rocket League",
    "Valorant",
    "Overwatch",
    "Apex Legends",
    "League of Legends",
    "Counter-Strike",
    "PUBG",
    "Marvel Rivals",
    "Genshin Impact",
    "World of Warcraft",
    "The Sims",
    "Candy Crush",
    "Subway Surfers",
    "Clash of Clans",
    "Clash Royale",
    "Angry Birds",
    "Temple Run",
    "Fruit Ninja",
    "Plants vs. Zombies",
    "Geometry Dash",
    "Flappy Bird",
    "Crossy Road",
    "Jetpack Joyride",
    "Cut the Rope",
    "Hill Climb Racing",
    "My Talking Tom",
    "Wordle",
    "Tetris",
    "Pac-Man",
    "Pong",
    "Space Invaders",
    "Snake",
    "Minesweeper",
    "Solitaire",
    "Sonic the Hedgehog",
    "Crash Bandicoot",
    "Spyro the Dragon",
    "Donkey Kong",
    "Kirby",
    "Luigi's Mansion",
    "Splatoon",
    "Nintendogs",
    "Cooking Mama",
    "Just Dance",
    "Guitar Hero",
    "Rock Band",
    "Dance Dance Revolution",
    "Wii Fit",
    "Red Dead Redemption 2",
    "The Last of Us",
    "God of War",
    "Marvel's Spider-Man",
    "Batman: Arkham City",
    "Assassin's Creed",
    "The Elder Scrolls V: Skyrim",
    "Fallout 4",
    "Cyberpunk 2077",
    "Elden Ring",
    "Dark Souls",
    "The Witcher 3",
    "Resident Evil",
    "Silent Hill",
    "Tomb Raider",
    "Uncharted",
    "Far Cry",
    "Hogwarts Legacy",
    "Star Wars Battlefront",
    "LEGO Star Wars",
    "Detroit: Become Human",
    "Hitman",
    "Portal",
    "Halo",
    "Destiny",
    "Doom",
    "Diablo",
    "SimCity",
    "Stardew Valley",
    "Terraria",
    "Five Nights at Freddy's",
    "Poppy Playtime",
    "Hello Neighbor",
    "Cuphead",
    "Undertale",
    "Dead by Daylight",
    "EA Sports FC / FIFA",
    "NBA 2K",
    "Madden NFL",
    "NHL",
    "WWE 2K",
    "Forza Horizon",
    "Gran Turismo",
    "Need for Speed",
    "Tony Hawk's Pro Skater",
    "Mortal Kombat",
    "Street Fighter",
    "Tekken",
    "Final Fantasy VII",
    "Kingdom Hearts",
    "LEGO Batman",
    "The Simpsons: Hit & Run",
    "Club Penguin",
    "Mario & Sonic at the Olympic Games"
  ],
  "Marvel": [
    "Spider-Man",
    "Iron Man",
    "Thor",
    "Hulk",
    "Black Widow",
    "Hawkeye",
    "Captain America",
    "Black Panther",
    "Doctor Strange",
    "Scarlet Witch",
    "Vision",
    "Thanos",
    "Loki",
    "Deadpool",
    "Wolverine",
    "Storm",
    "Cyclops",
    "Jean Grey",
    "Magneto",
    "Professor X",
    "Daredevil",
    "Moon Knight",
    "Ant-Man",
    "The Wasp",
    "Star-Lord",
    "Groot",
    "Rocket Raccoon",
    "Gamora",
    "Nebula",
    "Venom",
    "A Friend",
    "A La Mode",
    "A'di",
    "A'ishah",
    "A'Kane",
    "A'Kurru U'mbaya",
    "A'Lars",
    "A'Lars II",
    "A'Sai",
    "A'yin",
    "A-1 Sauce",
    "A-14",
    "A-Bomb (Warp World)",
    "A-Tuna",
    "A-Wet-man",
    "A. Summers",
    "A. Trabbold",
    "A. Verni",
    "A.C. Bradley",
    "A.C. O'Connor",
    "A.D. Doug",
    "A.G. Bell",
    "A.I. Sarah (Model 00-1468)",
    "A.J Dohertz",
    "A.J. (Backdoor Boys)",
    "A.J.",
    "A.J. Patton",
    "A.P.E.",
    "A3",
    "Aa-Gorn",
    "Aa-Thak",
    "Aadam",
    "Aaf Capmi Piap",
    "Aahi",
    "Aahmes",
    "Aaidan Blomfield",
    "Aala (Deity)",
    "Aala (Taa-an)",
    "Aalbort",
    "Aali",
    "Aaliyah Hardin",
    "Aamir",
    "Aamir Khan",
    "Aamshed",
    "Aan Taanu",
    "Aard",
    "Aardvark",
    "Aardwolf (Hyena Clan)",
    "Aarkus",
    "Aaron (Reporter)",
    "Aaron (Student)",
    "Aaron Aikman",
    "Aaron Alexander",
    "Aaron Amberson",
    "Aaron Carpenter",
    "Aaron Cashin",
    "Aaron Chord",
    "Aaron Davis",
    "Aaron Delgato",
    "Aaron Downing",
    "Aaron English",
    "Aaron Fischer",
    "Aaron Fox",
    "Aaron Heller",
    "Aaron Isaacs",
    "Aaron James",
    "Aaron Kearse",
    "Aaron Lopresti",
    "Aaron MacKenzie",
    "Aaron Nicholson",
    "Aaron Reece",
    "Aaron Rosenberg",
    "Aaron Salomon",
    "Aaron Schmidt",
    "Aaron Soames",
    "Aaron Sokoto",
    "Aaron Spiro",
    "Aaron Stack",
    "Aaron Stack (Impostor)",
    "Aaron Stankey",
    "Aaron the Aakon",
    "Aaron the Sorcerer",
    "Aaron Thorne",
    "Aaron Verne",
    "Aaron Warren",
    "Ab Waltin",
    "Abadon",
    "Abahla",
    "Aban",
    "Abarac",
    "Abbadona (Angel)",
    "Abbadona Hellgore",
    "Abbas",
    "Abbas al-Abbad",
    "Abbess Horror",
    "Abbey Sykes",
    "Abbot",
    "Abbot (U.S. Army)",
    "Abbot Shamescuttle",
    "Abbott",
    "Abby Davis",
    "Abby Levine",
    "Abby Miller",
    "Abby Morris",
    "Abby Rubin",
    "Abby-L",
    "Abd-el-Hazred",
    "Abdallah El-Faouly",
    "Abdi",
    "Abdol",
    "Abdomina",
    "Abdul",
    "Abdul Abismah",
    "Abdul Al-Rahman",
    "Abdul Ben Hassi",
    "Abdul Faoul",
    "Abdul Hurani",
    "Abdul Muhammed",
    "Abdul Qamar",
    "Abdul T'Chaka Rosenthal",
    "Abdul Tallosh",
    "Abdul Zu Fadh",
    "Abe Benerstein",
    "Abe Hargreaves",
    "Abe Jankovitz",
    "Abel",
    "Abel Barlow",
    "Abel Stack",
    "Abel Tennison",
    "Abelard",
    "Abelisk",
    "Abena",
    "Abena Adebayo",
    "Abeni",
    "Abeni (Mutant)",
    "Abercombie",
    "Aberdeen Angus",
    "Abib",
    "Abigail (Hollywood Hills Middle School)",
    "Abigail (Mutant)",
    "Abigail Arcane",
    "Abigail Baxter",
    "Abigail Boylen",
    "Abigail Brand",
    "Abigail Brown",
    "Abigail Burns",
    "Abigail Callaghan",
    "Abigail Colt",
    "Abigail Cowan",
    "Abigail Dunton",
    "Abigail Harkness",
    "Abigail Housman",
    "Abigail Jarvis",
    "Abigail Marigold",
    "Abigail Mercury (Clone)",
    "Abigail Mercury",
    "Abigail Slade",
    "Abigail Stewart",
    "Abigail Thanriaguiaxus",
    "Abigail Tyler",
    "Abigail Varden",
    "Abigail Verpoorten",
    "Abigail Whistler",
    "Abigail Williams",
    "Abigail Wright",
    "Abigor",
    "Abilash Tandon",
    "Abilene Cashman",
    "Abira",
    "Able Baker",
    "Able Doone",
    "Abner Abernaphy",
    "Abner Abernathy",
    "Abner Brody",
    "Abner Croit",
    "Abner Doolittle",
    "Abner Dunson",
    "Abner Ferris",
    "Abner Jenkins",
    "Abner Jonas",
    "Abner Little",
    "Abner Moorehead",
    "Abner Perkins",
    "Abner Perry",
    "Abominable Snowman (Howling Commandos)",
    "Abomination",
    "Abomination (Mojomedia)",
    "Abomination (Morlock)",
    "Abominite",
    "Abra and Cadabra",
    "Abraham",
    "Abraham Adamson",
    "Abraham Beame",
    "Abraham Brown",
    "Abraham Cabot",
    "Abraham Cornelius",
    "Abraham Donovan",
    "Abraham Erskine",
    "Abraham James",
    "Abraham Kieros",
    "Abraham Klein",
    "Abraham Lincoln (A.I.)",
    "Abraham Lincoln (Android)",
    "Abraham Lincoln",
    "Abraham Shoenstein",
    "Abraham Shooter",
    "Abraham Stoker",
    "Abraham Van Brunt",
    "Abraham van Helsing",
    "Abraham Verne",
    "Abraham Walker",
    "Abraham Whistler",
    "Abraham Wilson (Heroes Reborn)",
    "Abraham Zimmer",
    "Abraham Zimmer Jr.",
    "Abram",
    "Abrams (A.I.M.)",
    "Abraxas",
    "Abrogate",
    "Abscissa",
    "Absent-Minded Mac",
    "Absolon Mercator",
    "Absolute Sea Carnage",
    "Absorbing Bug",
    "Absorbing Man (Mojomedia)",
    "Absorbing Mouse",
    "Abstract",
    "Absynthe",
    "Absyrtus",
    "Abu Bakaar",
    "Abu Ben Hakim",
    "Abu Dakir",
    "Abu Ho Dadi",
    "Abu Mussan",
    "Abu Mūsā Jābir ibn Hayyān al-Azdi",
    "Abu-Ben Ar",
    "Abu-Jamal Rodriguez",
    "Abwama",
    "Abyss (Cosmic Sorcerer)",
    "Abyss",
    "Abyss (Entity)",
    "Abysss",
    "AC and DC",
    "AC-DC",
    "Acari",
    "Acba",
    "Accolon",
    "Ace",
    "Ace (G.R.A.M.P.A.)",
    "Ace (Pilot)",
    "Ace (S.H.I.E.L.D.)",
    "Ace Arnold",
    "Ace Fenton",
    "Ace Frehley",
    "Ace Maxwell",
    "Ace Peterson",
    "Ace Robinson",
    "Ace Spencer",
    "Ace Taggert",
    "Ace Turmbull",
    "Aces Wilde",
    "Achak",
    "Achebe",
    "Achelous",
    "Achille DiBacco",
    "Achilles",
    "Achilles (Helmut)",
    "Achlemedes",
    "Achmar",
    "Achmed Al-Khalad",
    "Achmed Al-Khalad (Heroes Reborn)",
    "Achmed El Gibár",
    "Achmed Korba",
    "Acid Queen",
    "Acidroid",
    "Acitua",
    "Acorn Annie",
    "Acrallidus",
    "Acrobat (1940s)",
    "Acrobat (Spider-Squad)",
    "Acroyear",
    "Active-Radio Spider",
    "Actor (Greek)",
    "Actor (Spy)",
    "Aculdi",
    "Ada",
    "Ada (Techno Sorceress)",
    "Ada Flores",
    "Adad",
    "Adahm",
    "Adai",
    "Adalbert Kamentin",
    "Adam",
    "Adam (Gideon)",
    "Adam (Mutant)",
    "Adam (Weapon VI Upgrade)",
    "Adam 3,031",
    "Adam Able",
    "Adam Austin",
    "Adam Aziz",
    "Adam Bentley",
    "Adam Berman",
    "Adam Blackveil",
    "Adam Brashear",
    "Adam Brigman",
    "Adam Carter",
    "Adam Casim",
    "Adam Clayton",
    "Adam Cooper",
    "Adam Cross",
    "Adam Crown",
    "Adam Del Re",
    "Adam Destine",
    "Adam Essex",
    "Adam Fisher",
    "Adam Frost",
    "Adam Gree",
    "Adam Gulliver",
    "Adam Harkins",
    "Adam Henderson",
    "Adam Hitt",
    "Adam II",
    "Adam Ishima",
    "Adam Jay",
    "Adam K'ad-Mon",
    "Adam Kane",
    "Adam Kipiniak",
    "Adam Kubert",
    "Adam Mann",
    "Adam Manna",
    "Adam Neramani",
    "Adam Neushuk",
    "Adam Peters",
    "Adam Pratt",
    "Adam Roderick",
    "Adam Rodney",
    "Adam Rossi",
    "Adam Rykland",
    "Adam Shockley",
    "Adam Simon",
    "Adam Spectre",
    "Adam Stokes",
    "Adam Torchia",
    "Adam Ware",
    "Adam Warlock",
    "Adam Warlox",
    "Adam Wright",
    "Adam Y",
    "Adam-X (Adorable X-Babies)",
    "Adamantine",
    "Adamo Dioli",
    "Adams (EET)",
    "Adams (Stark Industries)",
    "Adani",
    "Adanna",
    "Adanna Gui",
    "Addison Blackburn",
    "Addison Falk",
    "Addy Brock",
    "Adelbert Greywing",
    "Adele Gorton",
    "Adele Hawthorne",
    "Adele Racine",
    "Adele Santiago",
    "Adelicia von Krupp",
    "Adena",
    "Adept (Claw Sect)",
    "Adewale Ekoku",
    "Adhira Deol",
    "Adi (65,000,000 BC)",
    "Adimu Chiume",
    "Adina Johnson",
    "Adina Malcolm",
    "Adjudicator",
    "Adjunct",
    "Adlai Schmidt",
    "Administrator",
    "Administrator Porus",
    "Administrator Umbridge",
    "Admiral (Xandarian)",
    "Admiral Footsu",
    "Admiral Fukyama",
    "Admiral Jolnes",
    "Admiral Kiefer",
    "Admiral Nippo",
    "Admiral Nodope",
    "Admiral Perkins",
    "Admiral von Roeder",
    "Admiral White",
    "Adolf Hitler",
    "Adolf Hitler (Warp World)",
    "Adolf Impossible",
    "Adolfo Costa",
    "Adolfus Crane",
    "Adolphe Hiccup",
    "Adolphus",
    "Adolphus Williamson",
    "Adoma",
    "Adomox",
    "Adonai",
    "Adonis",
    "Adora",
    "Adoro",
    "Adramaelec",
    "Adri Nital",
    "Adria",
    "Adria Lafayette",
    "Adria Wagner",
    "Adrian (Cat)",
    "Adrian Castorp",
    "Adrian Chase",
    "Adrian Corbo",
    "Adrian Defoe",
    "Adrian Eiskalt",
    "Adrian Gray",
    "Adrian J. Watts",
    "Adrian Loring",
    "Adrian Luca",
    "Adrian Lynn",
    "Adrian Mortte",
    "Adrian Sammish",
    "Adrian Toomes (Doppelganger)",
    "Adrian Toomes",
    "Adrian Toomes (Noir)",
    "Adrian Toomes (Young)",
    "Adrian Turner",
    "Adrian Warsame",
    "Adriana Soria",
    "Adrianne Brown",
    "Adrianne Palicki",
    "Adriano Tumino",
    "Adriel",
    "Adrienne",
    "Adrienne Bowen",
    "Adrienne Brashear",
    "Adrienne Dore",
    "Adrienne Frost",
    "Adrienne Hatros",
    "Adron",
    "Adu Bey",
    "Adula",
    "Adulaysha",
    "Adur",
    "Adva",
    "Advanced Idea Mechanics (Tsum Tsum)",
    "Adversary",
    "Advisor",
    "Adwoma",
    "Aegeus",
    "Aegialues",
    "Aegir",
    "Aegis (Monster)",
    "Aegis (Proemial God)",
    "Aegisthus",
    "Aegle",
    "Aeish",
    "Ael-Dan",
    "Ael-Dann",
    "Aelfric",
    "Aelfyre Whitemane",
    "Aelfyre Whitemane (Warp World)",
    "Aelsa Featherwine of the Fay",
    "Aeltri",
    "Aeneas",
    "Aenetus",
    "Aentaros",
    "Aeon",
    "Aer",
    "Aera",
    "Aeric"
  ],
  "Disney": [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Cinderella",
    "Snow White",
    "Ariel",
    "Belle",
    "Aladdin",
    "Jasmine",
    "Simba",
    "Mufasa",
    "Elsa",
    "Anna",
    "Olaf",
    "Moana",
    "Maui",
    "Stitch",
    "Peter Pan",
    "Tinker Bell",
    "Buzz Lightyear",
    "Woody",
    "Lightning McQueen",
    "Nemo",
    "Dory",
    "Winnie the Pooh",
    "Tigger",
    "Rapunzel",
    "Cruella de Vil",
    "Maleficent",
    "Abigail the Cow",
    "Acer",
    "Abu",
    "Adolphus",
    "Accordion Owl",
    "Agent Heeley",
    "Achilles",
    "Alan Ripple",
    "Prince Achmed",
    "Alebrijes",
    "Aconcagua",
    "Alex (Float)",
    "Agent",
    "Alexander Hugo",
    "King Agnarr",
    "Chet Alexander",
    "Agnes De'Snake",
    "Alpha",
    "Agustín Madrigal",
    "Ambassador Auva",
    "Akela",
    "Ambassador Mira",
    "Aladar",
    "Ambassador Naos",
    "Aladar's Mother",
    "Amphibian King",
    "Anchor",
    "Alan-A-Dale",
    "The Ancient King",
    "Albertosaurus",
    "Mr. Andersen's Emotions",
    "Alice",
    "Mr. Andersen",
    "Alice Doe",
    "Mrs. Andersen",
    "Alice's Sister",
    "Bonnie Anderson",
    "Aliens (Chicken Little)",
    "Duncan P. Anderson",
    "Alley Cats",
    "Mrs. Anderson",
    "Alley Dogs",
    "Mr. Anderson",
    "Alligators",
    "André",
    "Queen Amaya",
    "Angel Kitty",
    "Captain Amelia",
    "Anger",
    "Amphitryon and Alcmene",
    "Anglerfish",
    "Anita Radcliffe",
    "Lord Angstrom",
    "Ankylosaurus",
    "Angus",
    "Animal Council",
    "Annette, Collette, and Danielle",
    "Ant Colony",
    "Antonio Madrigal's Animals",
    "Anxiety",
    "Antony Snootley",
    "Concetta and Pinuccia Aragosta",
    "Apatosaurus",
    "Archie",
    "Aphrodite",
    "Arlo",
    "Apollo (Fantasia)",
    "Arrival Agent",
    "Apollo (Hercules)",
    "Principal Arroyo",
    "Aracuan Bird",
    "Art",
    "Arawn",
    "Astro Blasters Robots",
    "Archaeopteryx",
    "Atlas (Toy Story)",
    "Archdeacon",
    "Atta",
    "Archimedes",
    "AUTO",
    "Ares (Hercules)",
    "Avel",
    "Queen Arianna",
    "Awe",
    "Axel",
    "Armpit Pete",
    "Miles Axlerod",
    "Mr. Arrow",
    "Alec Azam",
    "Artemis",
    "Mr. B",
    "Arthur (Wreck-It Ralph)",
    "Baby (Nona)",
    "Asha",
    "Babyface",
    "Athena",
    "The Badger",
    "Atlanteans",
    "Bailey",
    "Attila",
    "Bambino",
    "Audrey (Home on the Range)",
    "Banana Bread",
    "Audrey Ramirez",
    "Barbie",
    "Aunt Cass",
    "Barbra (Win or Lose)",
    "Aurora",
    "Barrel of Monkeys",
    "Avalonia",
    "Bass",
    "Avalonia Creatures",
    "Battlesaurs",
    "B.E.N.",
    "Becky (Finding Nemo)",
    "Baboons",
    "Ben (Monsters at Work)",
    "Baby Baboon",
    "Carla Benitez",
    "Baby Parasaurolophus",
    "Bensons",
    "Bacchus (Fantasia)",
    "Bernie Kropp",
    "The Backson",
    "Bernie Lumen",
    "Bad-Anon",
    "Francesco Bernoulli",
    "Dr. Badger",
    "Honey Best",
    "Bagheera",
    "Beta and Gamma",
    "Baitmouse",
    "Big Baby",
    "Ballerina",
    "Big D",
    "Balloon",
    "Thaddeus Bile",
    "Baloo",
    "Bill (Finding Nemo)",
    "Baltus Van Tassel",
    "Billy",
    "Bambi",
    "Billy's Toys",
    "Bambi's mother",
    "Billy, Goat, and Gruff",
    "Bandar-log",
    "Bing Bong",
    "Barry and Bob",
    "Bird",
    "Sir Bart",
    "Bird (Dug Days)",
    "Bartholomew",
    "Bird King",
    "Bashful",
    "Birds (For the Birds)",
    "Basil of Baker Street",
    "Bitey White",
    "Baylene",
    "Bizz Leapyear, Buzztron, and Blip Laserfist",
    "Baymax",
    "Blaze Manoukian",
    "Bayou Animals",
    "Blazey",
    "Bazeema",
    "Blenny",
    "The Bear",
    "Argus Blinks",
    "Bearoness Bear",
    "Bloofy",
    "Bears (Bongo)",
    "Blue Umbrella",
    "Beast",
    "The Blueberries",
    "Beaudreaux",
    "Bob Cutlass",
    "Beef Roger Crummchuk",
    "Randall Boggs",
    "The Bees",
    "Bomb Voyage",
    "Boo",
    "Ben Ali Gator",
    "Bookworm",
    "Ben and Lon",
    "Borna",
    "Berlioz",
    "Boss",
    "Bernard (The Rescuers)",
    "Brain Pods",
    "Miss Bianca",
    "Brazilian Helicopter Pilot",
    "Big Hero 6 (team)",
    "Brian Dyson",
    "Big Mama",
    "Brick",
    "Big Nose",
    "Brook Ripple",
    "Big Toot",
    "Bruce",
    "Mr. Big (Zootopia)",
    "Bryce",
    "Bill the Lizard",
    "Bubbha (The Good Dinosaur)",
    "Billie Doe",
    "Buck (The Good Dinosaur)",
    "Billie Robinson",
    "Buddy (Buzz Lightyear attractions)",
    "The Bimbettes",
    "Bullseye",
    "Birds (Beauty and the Beast)",
    "BURN-E",
    "Birds (Cinderella)",
    "Buster (Toy Story)",
    "Black Triangles",
    "Butch (The Good Dinosaur)",
    "Blake, Tom, and Billy",
    "Buttercup",
    "Blobfish (Moana)",
    "Alice Blue Bonnet",
    "Buzz Lightyear (Lightyear)",
    "Blue Fairy",
    "Buzz Lightyear (Star Command)",
    "Bob (Hercules)",
    "C.C. Stump",
    "Chief Bogo",
    "Caleb (Elio)",
    "Bolt",
    "Caligola",
    "Billy Bones (Treasure Planet)",
    "Capitano Briganti",
    "Madame Adelaide Bonfamille",
    "Captain B. McCrea",
    "Bongo the Bear",
    "Captain Suds",
    "The Bookseller",
    "Car-itters",
    "Boreas (Fantasia)",
    "Carl Reineroceros",
    "Boun",
    "Don Carlton",
    "Brachiosaurus",
    "Carole (Win or Lose)",
    "Bread-and-Butterflies",
    "Sally Carrera",
    "Brom Bones",
    "Cave Family",
    "Sheriff Sam Brown",
    "Cecilia (Coco)",
    "Brudus",
    "Centaurs",
    "Bruni",
    "Centaurs (Onward)",
    "Bruno (Cinderella)",
    "Los Chachalacos",
    "Bruno Madrigal",
    "Chairol Burnett",
    "Bruno's Rats",
    "Chalooby",
    "Brutish and Oafish Guards",
    "Charlie (Finding Nemo)",
    "Bruton",
    "Chatter Telephone",
    "Brutus and Nero",
    "Chef Skinner",
    "Cobra Bubbles",
    "Chelsea, Heidi, and Kara",
    "Buck",
    "Chen, Ping, Helen, and Lily",
    "Buck Cluck",
    "Cheryl",
    "Bucket (Hexed)",
    "Chicharrón",
    "Bucky and Pronk Oryx-Antlerson",
    "Chicken-Kev",
    "Bucky the Squirrel",
    "Child Detection Agency",
    "Bud Robinson",
    "Chuck E. Duck",
    "Buford (The Princess and the Frog)",
    "Chuckles the Clown",
    "Bulda",
    "Chum",
    "Bumble",
    "Chunk",
    "Burrito",
    "Ciccio and Guido",
    "Buster (Meet the Robinsons)",
    "Cindy (Bao)",
    "Mr. Busy",
    "Circus Bugs",
    "Butterflies (The Princess and the Frog)",
    "Clan Dingwall",
    "Buzzie, Flaps, Ziggy, and Dizzy",
    "Clan DunBroch",
    "Caledonian Boar",
    "Clan MacGuffin",
    "Sergeant Calhoun",
    "Clan Macintosh",
    "Dr. Calico",
    "Claudia (Partly Cloudy)",
    "Abigail Callaghan",
    "Santa Claus",
    "Mrs. Calloway",
    "Alistair Clawbottom",
    "Camilo Madrigal",
    "The Cleric",
    "Candlehead",
    "Clod",
    "King Candy",
    "Clouds (Partly Cloudy)",
    "Captain (101 Dalmatians)",
    "Cluckers",
    "Captain Crocodile",
    "Coach Dan",
    "Captain Hook",
    "Coach Roberts",
    "Captain Nathaniel Flint",
    "Cobweb",
    "Captain of the Guards",
    "Colette Tatou",
    "Card Soldiers",
    "Colt Bronco",
    "Caribou Stampede",
    "Combat Carl",
    "José Carioca",
    "Commander Burnside",
    "Carl the Robot",
    "Conan",
    "Carlotta",
    "Conner",
    "Carnotaurus",
    "Connie",
    "Casa Madrigal",
    "Construction Foreman Tom",
    "Casey (Make Mine Music)",
    "Construction Supervisor",
    "Casey Junior",
    "Construction Worker Steve",
    "Caspian",
    "Coral",
    "Castle Maids",
    "Corey the Manticore",
    "Caterpillar",
    "Corrections Officer",
    "Cattrick and Kitty Lynxley",
    "Cosmo (Lightyear)",
    "Caucus Race Animals",
    "The Crow",
    "Cauldron Born",
    "Mr. Crummyham",
    "Cave of Wonders",
    "Crush",
    "Centaurettes",
    "Cuddles the Alligator",
    "Curley Baker",
    "Inventco CEO",
    "The Curse Dragon",
    "Ceratosaurus",
    "Cutter",
    "Cerberus",
    "Cyclopes",
    "Cetus",
    "D-FIB",
    "Chaca",
    "Dad (Bao)",
    "Chairmouse",
    "Daffodil",
    "Prince Charming",
    "Daisy (Toy Story)",
    "Charon",
    "Dani (Inside Out 2)",
    "Charybdis",
    "Danny Swervez",
    "Chef Bouche",
    "Dante",
    "Chef Louis",
    "Dante (Elemental)",
    "Chernabog",
    "Darby Steel",
    "Chernabog's Minions",
    "Warp Darkmatter",
    "Cherubs",
    "Darla",
    "Cheshire Cat",
    "Darrell Cartrip",
    "Chi-Fu",
    "Dash Parr",
    "Chicha",
    "David (Monsters, Inc.)",
    "Chicks",
    "Andy Davis",
    "Chief",
    "Molly Davis",
    "Chief Benja",
    "Mrs. Davis",
    "Chief Tui",
    "Day",
    "Chip and Dale",
    "Evelyn Deavor",
    "Chispi",
    "Nelson Deavor",
    "Chloe Cluck",
    "Winston Deavor",
    "Declan",
    "Cinderella's Father",
    "Deep Dark Secret",
    "Cinderella's Mother",
    "Departure Agent",
    "Circus Animals",
    "Despair (Inside Out)",
    "Circus Elephants",
    "Destiny (Finding Dory)",
    "Ethan Clade",
    "Devon (Turning Red)",
    "Jaeger Clade",
    "Dewdrop",
    "Meridian Clade",
    "Dez (Soul)",
    "Searcher Clade",
    "Diane Shark",
    "The Clades",
    "Presto DiGiotagione",
    "Clarinet",
    "Wee Dingwall",
    "Clawhauser",
    "Diplodocus",
    "Clayton",
    "Discarded Fun Meal Toys",
    "Clayton's Men",
    "Disgust",
    "Cleo",
    "Django",
    "Clopin",
    "Doctor (Soul)",
    "Clowns",
    "Dolly",
    "Chicken Little (2005 character)",
    "Dolphina",
    "The Coachman's Assistants",
    "Don Crumlin",
    "The Coachman",
    "Doorman (Elemental)",
    "Coat Rack",
    "Cocoa",
    "Dot",
    "Cody (The Rescuers)",
    "Dr. Nutcase",
    "Cody's Mother",
    "Dragon the Cat",
    "Cogsworth",
    "Drips the Whale",
    "Collie",
    "Ducky and Bunny",
    "Colonel",
    "Dug",
    "Colorful Triangles",
    "Duke Caboom",
    "Compsognathus",
    "Dumpling (Bao)",
    "Condor",
    "Sandy Dunes",
    "Cookie (Atlantis: The Lost Empire)",
    "Durga",
    "Copper",
    "Airman Díaz",
    "Cotton (Zootopia)",
    "Earl (The Good Dinosaur)",
    "Cow (Mickey and the Beanstalk)",
    "Dale Earnhardt Jr.",
    "The Cows (101 Dalmatians)",
    "Eddy Ripple"
  ],
  "Celebrity": [
    "Tom Hanks",
    "Leonardo DiCaprio",
    "Brad Pitt",
    "Johnny Depp",
    "Robert Downey Jr.",
    "Denzel Washington",
    "Tom Cruise",
    "Will Smith",
    "Morgan Freeman",
    "Keanu Reeves",
    "Ryan Reynolds",
    "Ryan Gosling",
    "Chris Hemsworth",
    "Chris Evans",
    "Chris Pratt",
    "Hugh Jackman",
    "Mark Ruffalo",
    "Samuel L. Jackson",
    "Dwayne Johnson",
    "Vin Diesel",
    "Jason Momoa",
    "Jason Statham",
    "Jackie Chan",
    "Arnold Schwarzenegger",
    "Sylvester Stallone",
    "Bruce Willis",
    "Jim Carrey",
    "Adam Sandler",
    "Eddie Murphy",
    "Ben Stiller",
    "Steve Carell",
    "Kevin Hart",
    "Jack Black",
    "Seth Rogen",
    "Zac Efron",
    "Channing Tatum",
    "Paul Rudd",
    "Bradley Cooper",
    "Matt Damon",
    "Ben Affleck",
    "Christian Bale",
    "George Clooney",
    "Harrison Ford",
    "Robert De Niro",
    "Al Pacino",
    "Joaquin Phoenix",
    "Matthew McConaughey",
    "Jamie Foxx",
    "Idris Elba",
    "Michael B. Jordan",
    "Chadwick Boseman",
    "Daniel Craig",
    "Liam Neeson",
    "Ewan McGregor",
    "Orlando Bloom",
    "Daniel Radcliffe",
    "Rupert Grint",
    "Tom Holland",
    "Andrew Garfield",
    "Tobey Maguire",
    "Cillian Murphy",
    "Timothée Chalamet",
    "Pedro Pascal",
    "Will Ferrell",
    "Mike Myers",
    "Rowan Atkinson",
    "Terry Crews",
    "Bryan Cranston",
    "Danny DeVito",
    "Nicolas Cage",
    "John Travolta",
    "Patrick Stewart",
    "Ian McKellen",
    "James McAvoy",
    "Michael Fassbender",
    "Henry Cavill",
    "Jeremy Renner",
    "Anthony Mackie",
    "Sebastian Stan",
    "Macaulay Culkin",
    "Elijah Wood",
    "Jeff Goldblum",
    "Brendan Fraser",
    "Rami Malek",
    "Simu Liu",
    "Ken Jeong",
    "John Cena",
    "Dave Bautista",
    "Finn Wolfhard",
    "Matthew Perry",
    "Jerry Seinfeld",
    "Robin Williams",
    "Heath Ledger",
    "Bill Murray",
    "Owen Wilson",
    "Chris Rock",
    "Donald Glover",
    "Jake Gyllenhaal",
    "Benedict Cumberbatch",
    "Glen Powell",
    "Meryl Streep",
    "Sandra Bullock",
    "Julia Roberts",
    "Jennifer Lawrence",
    "Scarlett Johansson",
    "Margot Robbie",
    "Emma Stone",
    "Anne Hathaway",
    "Natalie Portman",
    "Angelina Jolie",
    "Jennifer Aniston",
    "Nicole Kidman",
    "Reese Witherspoon",
    "Cameron Diaz",
    "Drew Barrymore",
    "Kate Winslet",
    "Charlize Theron",
    "Halle Berry",
    "Viola Davis",
    "Zendaya",
    "Jenna Ortega",
    "Millie Bobby Brown",
    "Sydney Sweeney",
    "Florence Pugh",
    "Ana de Armas",
    "Gal Gadot",
    "Brie Larson",
    "Elizabeth Olsen",
    "Zoe Saldaña",
    "Emily Blunt",
    "Amy Adams",
    "Amanda Seyfried",
    "Rachel McAdams",
    "Emma Watson",
    "Kristen Stewart",
    "Dakota Johnson",
    "Blake Lively",
    "Megan Fox",
    "Jessica Alba",
    "Salma Hayek",
    "Sofia Vergara",
    "Priyanka Chopra",
    "Lucy Liu",
    "Michelle Yeoh",
    "Jamie Lee Curtis",
    "Sigourney Weaver",
    "Winona Ryder",
    "Catherine O'Hara",
    "Jennifer Coolidge",
    "Melissa McCarthy",
    "Taylor Swift",
    "Beyoncé",
    "Michael Jackson",
    "Elvis Presley",
    "Rihanna",
    "Adele",
    "Bruno Mars",
    "Ed Sheeran",
    "Justin Bieber",
    "Ariana Grande",
    "Lady Gaga",
    "Katy Perry",
    "Britney Spears",
    "Christina Aguilera",
    "Mariah Carey",
    "Whitney Houston",
    "Céline Dion",
    "Madonna",
    "Prince",
    "Janet Jackson",
    "Dua Lipa",
    "Billie Eilish",
    "Olivia Rodrigo",
    "Sabrina Carpenter",
    "Harry Styles",
    "Shawn Mendes",
    "Camila Cabello",
    "Doja Cat",
    "SZA",
    "The Weeknd",
    "Drake",
    "Post Malone",
    "Eminem",
    "Snoop Dogg",
    "Jay-Z",
    "Kanye West",
    "Travis Scott",
    "Kendrick Lamar",
    "Nicki Minaj",
    "Cardi B",
    "Megan Thee Stallion",
    "Lil Wayne",
    "50 Cent",
    "Ice Cube",
    "Tupac Shakur",
    "The Notorious B.I.G.",
    "Pitbull",
    "Usher",
    "Chris Brown",
    "Alicia Keys",
    "Jennifer Lopez",
    "Shakira",
    "Bad Bunny",
    "Daddy Yankee",
    "Enrique Iglesias",
    "Ricky Martin",
    "Selena Quintanilla",
    "Karol G",
    "Freddie Mercury",
    "Elton John",
    "Billy Joel",
    "Stevie Wonder",
    "Bob Marley",
    "John Lennon",
    "Paul McCartney",
    "Mick Jagger",
    "David Bowie",
    "Bruce Springsteen",
    "Jon Bon Jovi",
    "Ozzy Osbourne",
    "Kurt Cobain",
    "Axl Rose",
    "Slash",
    "Steven Tyler",
    "Phil Collins",
    "Sting",
    "Cher",
    "Tina Turner",
    "Dolly Parton",
    "Shania Twain",
    "Carrie Underwood",
    "Morgan Wallen",
    "Luke Combs",
    "Gwen Stefani",
    "Pink",
    "Kelly Clarkson",
    "Avril Lavigne",
    "Justin Timberlake",
    "Pharrell Williams",
    "Adam Levine",
    "Charlie Puth",
    "John Legend",
    "Jason Derulo",
    "Akon",
    "Sean Paul",
    "Frank Sinatra",
    "Aretha Franklin",
    "Jungkook (BTS)",
    "Jennie (BLACKPINK)",
    "Rosé (BLACKPINK)"
  ],
  "Music": [
    "Rock Around the Clock",
    "Johnny B. Goode",
    "Jailhouse Rock",
    "Hound Dog",
    "Blue Suede Shoes",
    "Great Balls of Fire",
    "La Bamba",
    "That'll Be the Day",
    "Wake Up Little Susie",
    "Only You",
    "Stand by Me",
    "At Last",
    "What a Wonderful World",
    "Unchained Melody",
    "Can't Help Falling in Love",
    "My Girl",
    "Respect",
    "I Heard It Through the Grapevine",
    "Ain't No Mountain High Enough",
    "You Can't Hurry Love",
    "Stop! In the Name of Love",
    "Dancing in the Street",
    "Be My Baby",
    "Will You Love Me Tomorrow",
    "Build Me Up Buttercup",
    "Twist and Shout",
    "I Want to Hold Your Hand",
    "A Hard Day's Night",
    "Help!",
    "Yesterday",
    "Hey Jude",
    "Let It Be",
    "Come Together",
    "Here Comes the Sun",
    "Paint It, Black",
    "(I Can't Get No) Satisfaction",
    "House of the Rising Sun",
    "Good Vibrations",
    "California Dreamin'",
    "Mrs. Robinson",
    "Sweet Caroline",
    "Brown Eyed Girl",
    "Son of a Preacher Man",
    "Suspicious Minds",
    "Proud Mary",
    "Raindrops Keep Fallin' on My Head",
    "Sugar, Sugar",
    "Happy Together",
    "Imagine",
    "Your Song",
    "Tiny Dancer",
    "Rocket Man",
    "Piano Man",
    "American Pie",
    "Take Me Home, Country Roads",
    "Jolene",
    "Dreams",
    "Go Your Own Way",
    "Hotel California",
    "Take It Easy",
    "Life in the Fast Lane",
    "Bohemian Rhapsody",
    "Don't Stop Me Now",
    "We Will Rock You",
    "We Are the Champions",
    "Somebody to Love",
    "Another One Bites the Dust",
    "Dancing Queen",
    "Mamma Mia",
    "Waterloo",
    "Stayin' Alive",
    "How Deep Is Your Love",
    "Night Fever",
    "I Will Survive",
    "Y.M.C.A.",
    "Le Freak",
    "September",
    "Let's Stay Together",
    "Superstition",
    "Isn't She Lovely",
    "Let's Get It On",
    "What's Going On",
    "Lean on Me",
    "Killing Me Softly with His Song",
    "You're So Vain",
    "Margaritaville",
    "Sweet Home Alabama",
    "Free Bird",
    "More Than a Feeling",
    "Carry on Wayward Son",
    "The Boys Are Back in Town",
    "Play That Funky Music",
    "Don't Go Breaking My Heart",
    "You're the One That I Want",
    "Hopelessly Devoted to You",
    "I Want You Back",
    "Billie Jean",
    "Beat It",
    "Thriller",
    "Man in the Mirror",
    "Like a Prayer",
    "Like a Virgin",
    "Material Girl",
    "Girls Just Want to Have Fun",
    "Time After Time",
    "I Wanna Dance with Somebody",
    "Wake Me Up Before You Go-Go",
    "Careless Whisper",
    "Faith",
    "Footloose",
    "Flashdance... What a Feeling",
    "Take on Me",
    "Africa",
    "Everybody Wants to Rule the World",
    "Sweet Dreams (Are Made of This)",
    "Don't You (Forget About Me)",
    "Livin' on a Prayer",
    "You Give Love a Bad Name",
    "Wanted Dead or Alive",
    "Eye of the Tiger",
    "The Final Countdown",
    "Don't Stop Believin'",
    "Open Arms",
    "Any Way You Want It",
    "Summer of '69",
    "Heaven",
    "Pour Some Sugar on Me",
    "Under Pressure",
    "The Power of Love",
    "Heaven Is a Place on Earth",
    "Eternal Flame",
    "Total Eclipse of the Heart",
    "What's Love Got to Do with It",
    "Private Dancer",
    "Karma Chameleon",
    "Jessie's Girl",
    "Walking on Sunshine",
    "99 Luftballons",
    "You Spin Me Round (Like a Record)",
    "Tainted Love",
    "Mickey",
    "Maniac",
    "Red Red Wine",
    "Every Breath You Take",
    "With or Without You",
    "The Boys of Summer",
    "Fast Car",
    "The Way You Make Me Feel",
    "Smells Like Teen Spirit",
    "Wonderwall",
    "Don't Look Back in Anger",
    "I Want It That Way",
    "Everybody (Backstreet's Back)",
    "Baby One More Time",
    "Toxic",
    "Genie in a Bottle",
    "No Scrubs",
    "Waterfalls",
    "I'll Make Love to You",
    "I Swear",
    "Because You Loved Me",
    "My Heart Will Go On",
    "I Will Always Love You",
    "Hero",
    "Fantasy",
    "Vision of Love",
    "Nothing Compares 2 U",
    "Torn",
    "Kiss Me",
    "Iris",
    "Semi-Charmed Life",
    "All Star",
    "MMMBop",
    "Wannabe",
    "No Diggity",
    "This Is How We Do It",
    "Return of the Mack",
    "U Can't Touch This",
    "Jump",
    "Baby Got Back",
    "Ice Ice Baby",
    "California Love",
    "Juicy",
    "Hypnotize",
    "Killing Me Softly",
    "Gangsta's Paradise",
    "Mo Money Mo Problems",
    "Losing My Religion",
    "Zombie",
    "Creep",
    "Basket Case",
    "What's Up?",
    "Crazy in Love",
    "Single Ladies (Put a Ring on It)",
    "Umbrella",
    "Hips Don't Lie",
    "Whenever, Wherever",
    "Complicated",
    "Sk8er Boi",
    "Since U Been Gone",
    "Because of You",
    "Beautiful",
    "Yeah!",
    "DJ Got Us Fallin' in Love",
    "Hot in Herre",
    "In Da Club",
    "Gold Digger",
    "Stronger",
    "Hey Ya!",
    "Ms. Jackson",
    "Crazy",
    "Promiscuous",
    "Maneater",
    "SexyBack",
    "Cry Me a River",
    "Rock Your Body",
    "Poker Face",
    "Just Dance",
    "Bad Romance",
    "I Gotta Feeling",
    "Boom Boom Pow",
    "Party in the U.S.A.",
    "Bleeding Love",
    "Apologize",
    "The Reason",
    "How You Remind Me",
    "Drops of Jupiter",
    "Beautiful Soul",
    "A Thousand Miles",
    "Pocketful of Sunshine",
    "Unwritten",
    "Put Your Records On",
    "Mr. Brightside",
    "Use Somebody",
    "Viva la Vida",
    "Clocks",
    "Boulevard of Broken Dreams",
    "Sugar, We're Goin Down",
    "Misery Business",
    "I'm Yours",
    "Love Story",
    "Rolling in the Deep",
    "Someone Like You",
    "Firework",
    "Teenage Dream",
    "Roar",
    "Shake It Off",
    "Blank Space",
    "Bad Blood",
    "Style",
    "Uptown Funk",
    "Just the Way You Are",
    "Grenade",
    "Locked Out of Heaven",
    "Happy",
    "Get Lucky",
    "Call Me Maybe",
    "What Makes You Beautiful",
    "Story of My Life",
    "Shape of You",
    "Perfect",
    "Thinking Out Loud",
    "Sorry",
    "Love Yourself",
    "What Do You Mean?",
    "Baby",
    "Counting Stars",
    "Radioactive",
    "Demons",
    "Pompeii",
    "Rude",
    "Royals",
    "Cheap Thrills",
    "Chandelier",
    "Wrecking Ball",
    "Party Rock Anthem",
    "Timber",
    "Tik Tok",
    "We Found Love",
    "Only Girl (In the World)",
    "Diamonds",
    "Starboy",
    "Blinding Lights",
    "Save Your Tears",
    "Can't Feel My Face",
    "Old Town Road",
    "Sunflower",
    "Circles",
    "Havana",
    "Señorita",
    "Despacito",
    "Levitating",
    "Don't Start Now",
    "Watermelon Sugar",
    "As It Was",
    "Drivers License",
    "Good 4 U",
    "Flowers",
    "Espresso",
    "Birds of a Feather"
  ],
  "华语音乐": [
    "月亮代表我的心",
    "甜蜜蜜",
    "小城故事",
    "我只在乎你",
    "漫步人生路",
    "夜来香",
    "但愿人长久",
    "恰似你的温柔",
    "何日君再来",
    "在水一方",
    "橄榄树",
    "外婆的澎湖湾",
    "童年",
    "恋曲1990",
    "光阴的故事",
    "明天会更好",
    "龙的传人",
    "一场游戏一场梦",
    "梦醒时分",
    "爱的代价",
    "伤痕",
    "领悟",
    "至少还有你",
    "听海",
    "剪爱",
    "味道",
    "征服",
    "勇气",
    "后来",
    "很爱很爱你",
    "为爱痴狂",
    "爱如潮水",
    "过火",
    "别怕我伤心",
    "一千个伤心的理由",
    "吻别",
    "忘记你我做不到",
    "海阔天空",
    "光辉岁月",
    "真的爱你",
    "喜欢你",
    "不再犹豫",
    "情人",
    "大地",
    "灰色轨迹",
    "风继续吹",
    "沉默是金",
    "倩女幽魂",
    "当年情",
    "怪你过分美丽",
    "追",
    "千千阙歌",
    "夕阳之歌",
    "女人花",
    "似是故人来",
    "胭脂扣",
    "红日",
    "月半小夜曲",
    "一生不变",
    "护花使者",
    "富士山下",
    "十年",
    "好久不见",
    "浮夸",
    "淘汰",
    "爱情转移",
    "明年今日",
    "最佳损友",
    "单车",
    "K歌之王",
    "遥远的她",
    "饿狼传说",
    "只想一生跟你走",
    "每天爱你多一些",
    "李香兰",
    "一路上有你",
    "她来听我的演唱会",
    "心如刀割",
    "一起走过的日子",
    "忘情水",
    "冰雨",
    "男人哭吧不是罪",
    "练习",
    "谢谢你的爱",
    "偏偏喜欢你",
    "一生何求",
    "朋友",
    "沧海一声笑",
    "男儿当自强",
    "铁血丹心",
    "上海滩",
    "万水千山总是情",
    "红豆",
    "我愿意",
    "流年",
    "棋子",
    "天空",
    "矜持",
    "人间",
    "白天不懂夜的黑",
    "七里香",
    "晴天",
    "稻香",
    "青花瓷",
    "夜曲",
    "简单爱",
    "不能说的秘密",
    "告白气球",
    "东风破",
    "发如雪",
    "听妈妈的话",
    "菊花台",
    "一路向北",
    "搁浅",
    "安静",
    "彩虹",
    "蒲公英的约定",
    "珊瑚海",
    "龙卷风",
    "可爱女人",
    "半岛铁盒",
    "以父之名",
    "最长的电影",
    "说好的幸福呢",
    "退后",
    "本草纲目",
    "双截棍",
    "牛仔很忙",
    "千里之外",
    "江南",
    "小酒窝",
    "修炼爱情",
    "她说",
    "可惜没如果",
    "曹操",
    "背对背拥抱",
    "那些你很冒险的梦",
    "不为谁而作的歌",
    "关键词",
    "一千年以后",
    "简简单单",
    "豆浆油条",
    "美人鱼",
    "学不会",
    "交换余生",
    "倔强",
    "温柔",
    "突然好想你",
    "知足",
    "恋爱ING",
    "你不是真正的快乐",
    "离开地球表面",
    "拥抱",
    "干杯",
    "我不愿让你一个人",
    "后来的我们",
    "盛夏光年",
    "中国话",
    "不想长大",
    "波斯猫",
    "美丽新世界",
    "热带雨林",
    "恋人未满",
    "遇见",
    "天黑黑",
    "我怀念的",
    "开始懂了",
    "绿光",
    "逆光",
    "日不落",
    "倒带",
    "说爱你",
    "舞娘",
    "看我七十二变",
    "爱情三十六计",
    "特务J",
    "隐形的翅膀",
    "欧若拉",
    "遗失的美好",
    "亲爱的那不是爱情",
    "淋雨一直走",
    "唯一",
    "大城小爱",
    "你不知道的事",
    "我们的歌",
    "依然爱你",
    "爱很简单",
    "普通朋友",
    "今天你要嫁给我",
    "小镇姑娘",
    "飞机场的十点半",
    "不得不爱",
    "快乐崇拜",
    "爱转角",
    "精舞门",
    "恋爱达人",
    "爱不单行",
    "暖暖",
    "可惜不是你",
    "分手快乐",
    "会呼吸的痛",
    "宁夏",
    "情歌",
    "没有如果",
    "童话",
    "第一次",
    "约定",
    "掌心",
    "最重要的决定",
    "一个像夏天一个像秋天",
    "那些花儿",
    "老鼠爱大米",
    "两只蝴蝶",
    "香水有毒",
    "求佛",
    "秋天不回来",
    "月亮之上",
    "自由飞翔",
    "荷塘月色",
    "最炫民族风",
    "小苹果",
    "爱情买卖",
    "伤不起",
    "一万个理由",
    "该死的温柔",
    "爱你",
    "当你",
    "小情歌",
    "无与伦比的美丽",
    "我好想你",
    "你被写在我的歌里",
    "那些年",
    "小幸运",
    "成全",
    "说谎",
    "演员",
    "丑八怪",
    "绅士",
    "刚刚好",
    "认真的雪",
    "你还要我怎样",
    "意外",
    "天外来物",
    "泡沫",
    "光年之外",
    "来自天堂的魔鬼",
    "倒数",
    "句号",
    "多远都要在一起",
    "再见",
    "以后别做朋友",
    "你，好不好？",
    "怎么了",
    "如果雨之后",
    "永不失联的爱",
    "烟火里的尘埃",
    "好想爱这个世界啊",
    "国王与乞丐",
    "起风了",
    "体面",
    "说散就散",
    "追光者",
    "往后余生",
    "年少有为",
    "消愁",
    "像我这样的人",
    "平凡的一天",
    "无名的人",
    "可能否",
    "你的答案",
    "少年",
    "芒种",
    "大鱼",
    "凉凉",
    "左手指月",
    "不染",
    "如愿",
    "孤勇者",
    "乌梅子酱",
    "嘉宾",
    "哪里都是你",
    "悬溺",
    "偏爱",
    "有何不可",
    "素颜",
    "雅俗共赏",
    "想见你想见你想见你",
    "刻在我心底的名字",
    "如果可以",
    "带我去找夜生活",
    "披星戴月的想你",
    "爱人错过",
    "在这座城市遗失了你",
    "给你一瓶魔法药水",
    "好不容易",
    "天后",
    "王妃",
    "怎么说我不爱你",
    "洋葱",
    "想自由"
  ]
};
