// Generated static word banks. The live game does not call external APIs.
window.CHARADES_CATEGORIES = {
  "Animals": [
    "Elephant",
    "Penguin",
    "Giraffe",
    "Kangaroo",
    "Dolphin",
    "Octopus",
    "Crocodile",
    "Flamingo",
    "Gorilla",
    "Butterfly",
    "Shark",
    "Tiger",
    "Lion",
    "Monkey",
    "Rabbit",
    "Turtle",
    "Snake",
    "Horse",
    "Zebra",
    "Owl",
    "Panda",
    "Koala",
    "Wolf",
    "Fox",
    "Bear",
    "Eagle",
    "Peacock",
    "Camel",
    "Hippo",
    "Rhino",
    "Aardvark",
    "Abyssinian",
    "Adelie Penguin",
    "Affenpinscher",
    "Afghan Hound",
    "African Bush Elephant",
    "African Civet",
    "African Clawed Frog",
    "African Forest Elephant",
    "African Palm Civet",
    "African Penguin",
    "African Tree Toad",
    "African Wild Dog",
    "Ainu Dog",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alaskan Malamute",
    "Albatross",
    "Aldabra Giant Tortoise",
    "Alligator",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd Dog",
    "Angelfish",
    "Ant",
    "Anteater",
    "Antelope",
    "Appenzeller Dog",
    "Arctic Fox",
    "Arctic Hare",
    "Arctic Wolf",
    "Armadillo",
    "Asian Elephant",
    "Asian Giant Hornet",
    "Asian Palm Civet",
    "Asiatic Black Bear",
    "Australian Cattle Dog",
    "Australian Kelpie Dog",
    "Australian Mist",
    "Australian Shepherd",
    "Australian Terrier",
    "Avocet",
    "Axolotl",
    "Aye Aye",
    "Baboon",
    "Bactrian Camel",
    "Badger",
    "Balinese",
    "Banded Palm Civet",
    "Bandicoot",
    "Barb",
    "Barn Owl",
    "Barnacle",
    "Barracuda",
    "Basenji Dog",
    "Basking Shark",
    "Basset Hound",
    "Bat",
    "Bavarian Mountain Hound",
    "Beagle",
    "Bearded Collie",
    "Bearded Dragon",
    "Beaver",
    "Bedlington Terrier",
    "Beetle",
    "Bengal Tiger",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Binturong",
    "Bird",
    "Birds Of Paradise",
    "Birman",
    "Bison",
    "Black Bear",
    "Black Rhinoceros",
    "Black Russian Terrier",
    "Black Widow Spider",
    "Bloodhound",
    "Blue Lacy Dog",
    "Blue Whale",
    "Bluetick Coonhound",
    "Bobcat",
    "Bolognese Dog",
    "Bombay",
    "Bongo",
    "Bonobo",
    "Booby",
    "Border Collie",
    "Border Terrier",
    "Bornean Orang-utan",
    "Borneo Elephant",
    "Boston Terrier",
    "Bottle Nosed Dolphin",
    "Boxer Dog",
    "Boykin Spaniel",
    "Brazilian Terrier",
    "Brown Bear",
    "Budgerigar",
    "Buffalo",
    "Bull Mastiff",
    "Bull Shark",
    "Bull Terrier",
    "Bulldog",
    "Bullfrog",
    "Bumble Bee",
    "Burmese",
    "Burrowing Frog",
    "Butterfly Fish",
    "Caiman",
    "Caiman Lizard",
    "Cairn Terrier",
    "Canaan Dog",
    "Capybara",
    "Caracal",
    "Carolina Dog",
    "Cassowary",
    "Cat",
    "Caterpillar",
    "Catfish",
    "Cavalier King Charles Spaniel",
    "Centipede",
    "Cesky Fousek",
    "Chameleon",
    "Chamois",
    "Cheetah",
    "Chesapeake Bay Retriever",
    "Chicken",
    "Chihuahua",
    "Chimpanzee",
    "Chinchilla",
    "Chinese Crested Dog",
    "Chinook",
    "Chinstrap Penguin",
    "Chipmunk",
    "Chow Chow",
    "Cichlid",
    "Clouded Leopard",
    "Clown Fish",
    "Clumber Spaniel",
    "Coati",
    "Cockroach",
    "Collared Peccary",
    "Collie",
    "Common Buzzard",
    "Common Frog",
    "Common Loon",
    "Common Toad",
    "Coral",
    "Cottontop Tamarin",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crab-Eating Macaque",
    "Crane",
    "Crested Penguin",
    "Cross River Gorilla",
    "Curly Coated Retriever",
    "Cuscus",
    "Cuttlefish",
    "Dachshund",
    "Dalmatian",
    "Darwin's Frog",
    "Deer",
    "Desert Tortoise",
    "Deutsche Bracke",
    "Dhole",
    "Dingo",
    "Discus",
    "Doberman Pinscher",
    "Dodo",
    "Dog",
    "Dogo Argentino",
    "Dogue De Bordeaux",
    "Donkey",
    "Dormouse",
    "Dragonfly",
    "Drever",
    "Duck",
    "Dugong",
    "Dunker",
    "Dusky Dolphin",
    "Dwarf Crocodile",
    "Earwig",
    "Eastern Gorilla",
    "Eastern Lowland Gorilla",
    "Echidna",
    "Edible Frog",
    "Egyptian Mau",
    "Electric Eel",
    "Elephant Seal",
    "Elephant Shrew",
    "Emperor Penguin",
    "Emperor Tamarin",
    "Emu",
    "English Cocker Spaniel",
    "English Shepherd",
    "English Springer Spaniel",
    "Entlebucher Mountain Dog",
    "Epagneul Pont Audemer",
    "Eskimo Dog",
    "Estrela Mountain Dog",
    "Falcon",
    "Fennec Fox",
    "Ferret",
    "Field Spaniel",
    "Fin Whale",
    "Finnish Spitz",
    "Fire-Bellied Toad",
    "Fish",
    "Fishing Cat",
    "Flat Coat Retriever",
    "Flounder",
    "Fly",
    "Flying Squirrel",
    "Fossa",
    "Fox Terrier",
    "French Bulldog",
    "Frigatebird",
    "Frilled Lizard",
    "Frog",
    "Fur Seal",
    "Galapagos Penguin",
    "Galapagos Tortoise",
    "Gar",
    "Gecko",
    "Gentoo Penguin",
    "Geoffroys Tamarin",
    "Gerbil",
    "German Pinscher",
    "German Shepherd",
    "Gharial",
    "Giant African Land Snail",
    "Giant Clam",
    "Giant Panda Bear",
    "Giant Schnauzer",
    "Gibbon",
    "Gila Monster",
    "Glass Lizard",
    "Glow Worm",
    "Goat",
    "Golden Lion Tamarin",
    "Golden Oriole",
    "Golden Retriever",
    "Goose",
    "Gopher",
    "Grasshopper",
    "Great Dane",
    "Great White Shark",
    "Greater Swiss Mountain Dog",
    "Green Bee-Eater",
    "Greenland Dog",
    "Grey Mouse Lemur",
    "Grey Reef Shark",
    "Grey Seal",
    "Greyhound",
    "Grizzly Bear",
    "Grouse",
    "Guinea Fowl",
    "Guinea Pig",
    "Guppy",
    "Hammerhead Shark",
    "Hamster",
    "Hare",
    "Harrier",
    "Havanese",
    "Hedgehog",
    "Hercules Beetle",
    "Hermit Crab",
    "Heron",
    "Highland Cattle",
    "Himalayan",
    "Hippopotamus",
    "Honey Bee",
    "Horn Shark",
    "Horned Frog",
    "Horseshoe Crab",
    "Howler Monkey",
    "Human",
    "Humboldt Penguin",
    "Hummingbird",
    "Humpback Whale",
    "Hyena",
    "Ibis",
    "Ibizan Hound",
    "Iguana",
    "Impala",
    "Indian Elephant",
    "Indian Palm Squirrel",
    "Indian Rhinoceros",
    "Indian Star Tortoise",
    "Indochinese Tiger",
    "Indri",
    "Insect",
    "Irish Setter",
    "Irish WolfHound",
    "Jack Russel",
    "Jackal",
    "Jaguar",
    "Japanese Chin",
    "Japanese Macaque",
    "Javan Rhinoceros",
    "Javanese",
    "Jellyfish",
    "Kakapo",
    "Keel Billed Toucan",
    "Killer Whale",
    "King Crab",
    "King Penguin",
    "Kingfisher",
    "Kiwi",
    "Komodo Dragon",
    "Kudu",
    "Labradoodle",
    "Labrador Retriever",
    "Ladybird",
    "Leaf-Tailed Gecko",
    "Lemming",
    "Lemur",
    "Leopard",
    "Leopard Cat",
    "Leopard Seal",
    "Leopard Tortoise",
    "Liger",
    "Lionfish",
    "Little Penguin",
    "Lizard",
    "Llama",
    "Lobster",
    "Long-Eared Owl",
    "Lynx",
    "Macaroni Penguin",
    "Macaw",
    "Magellanic Penguin",
    "Magpie",
    "Maine Coon",
    "Malayan Civet",
    "Malayan Tiger",
    "Maltese",
    "Manatee",
    "Mandrill",
    "Manta Ray",
    "Marine Toad",
    "Markhor",
    "Marsh Frog",
    "Masked Palm Civet",
    "Mastiff",
    "Mayfly",
    "Meerkat",
    "Millipede",
    "Minke Whale",
    "Mole",
    "Molly",
    "Mongoose",
    "Mongrel",
    "Monitor Lizard",
    "Monte Iberia Eleuth",
    "Moorhen",
    "Moose",
    "Moray Eel",
    "Moth",
    "Mountain Gorilla",
    "Mountain Lion",
    "Mouse",
    "Mule",
    "Neanderthal",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Newt",
    "Nightingale",
    "Norfolk Terrier",
    "Norwegian Forest",
    "Numbat",
    "Nurse Shark",
    "Ocelot",
    "Okapi",
    "Old English Sheepdog",
    "Olm",
    "Opossum",
    "Orang-utan",
    "Ostrich",
    "Otter",
    "Oyster",
    "Pademelon",
    "Panther",
    "Parrot",
    "Patas Monkey",
    "Pekingese",
    "Pelican",
    "Persian",
    "Pheasant",
    "Pied Tamarin",
    "Pig",
    "Pika",
    "Pike",
    "Pink Fairy Armadillo",
    "Piranha",
    "Platypus",
    "Pointer",
    "Poison Dart Frog",
    "Polar Bear",
    "Pond Skater",
    "Poodle",
    "Pool Frog",
    "Porcupine",
    "Possum",
    "Prawn",
    "Proboscis Monkey",
    "Puffer Fish",
    "Puffin",
    "Pug",
    "Puma",
    "Purple Emperor",
    "Puss Moth",
    "Pygmy Hippopotamus",
    "Pygmy Marmoset",
    "Quail",
    "Quetzal",
    "Quokka",
    "Quoll",
    "Raccoon",
    "Raccoon Dog",
    "Radiated Tortoise",
    "Ragdoll",
    "Rat",
    "Rattlesnake",
    "Red Knee Tarantula",
    "Red Panda",
    "Red Wolf",
    "Red-handed Tamarin",
    "Reindeer",
    "Rhinoceros",
    "River Dolphin",
    "River Turtle",
    "Robin",
    "Rock Hyrax",
    "Rockhopper Penguin",
    "Roseate Spoonbill",
    "Rottweiler",
    "Royal Penguin",
    "Russian Blue",
    "Sabre-Toothed Tiger",
    "Saint Bernard",
    "Salamander",
    "Sand Lizard",
    "Saola",
    "Scorpion",
    "Scorpion Fish",
    "Sea Dragon",
    "Sea Lion",
    "Sea Otter",
    "Sea Slug",
    "Sea Squirt",
    "Sea Turtle",
    "Sea Urchin",
    "Seahorse",
    "Seal",
    "Serval",
    "Sheep",
    "Shih Tzu",
    "Shrimp",
    "Siamese"
  ],
  "Movies": [
    "Titanic",
    "Avatar",
    "Frozen",
    "Shrek",
    "Jaws",
    "The Avengers",
    "Jurassic Park",
    "Toy Story",
    "The Lion King",
    "Finding Nemo",
    "Spider-Man",
    "Iron Man",
    "Black Panther",
    "The Dark Knight",
    "Home Alone",
    "Harry Potter",
    "The Hunger Games",
    "Star Wars",
    "The Matrix",
    "Ghostbusters",
    "Barbie",
    "Oppenheimer",
    "The Incredibles",
    "Moana",
    "Aladdin",
    "Cars",
    "Ratatouille",
    "The Notebook",
    "Mean Girls",
    "Interstellar",
    "Minions",
    "Guardians of the Galaxy",
    "Mad Max: Fury Road",
    "Jurassic World",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Dawn of the Planet of the Apes",
    "The Hunger Games: Mockingjay - Part 1",
    "Big Hero 6",
    "Terminator Genisys",
    "Captain America: Civil War",
    "The Martian",
    "Inception",
    "Batman v Superman: Dawn of Justice",
    "Fight Club",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Teenage Mutant Ninja Turtles",
    "Gone Girl",
    "Pixels",
    "Fury",
    "X-Men: Apocalypse",
    "Pirates of the Caribbean: At World's End",
    "Rise of the Planet of the Apes",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Despicable Me 2",
    "Pirates of the Caribbean: On Stranger Tides",
    "Avengers: Age of Ultron",
    "Harry Potter and the Chamber of Secrets",
    "Tomorrowland",
    "Inside Out",
    "The Hunger Games: Mockingjay - Part 2",
    "Brave",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: The Battle of the Five Armies",
    "Ant-Man",
    "X-Men: Days of Future Past",
    "Transformers: Age of Extinction",
    "Spider-Man 3",
    "Night at the Museum: Secret of the Tomb",
    "Batman Begins",
    "Mission: Impossible - Rogue Nation",
    "Despicable Me",
    "Maze Runner: The Scorch Trials",
    "The Dark Knight Rises",
    "Maleficent",
    "Gravity",
    "Harry Potter and the Philosopher's Stone",
    "Bruce Almighty",
    "The Fifth Element",
    "The Hobbit: An Unexpected Journey",
    "Quantum of Solace",
    "Spectre",
    "The Twilight Saga: Eclipse",
    "The Lord of the Rings: The Two Towers",
    "Monsters, Inc.",
    "Men in Black",
    "Insurgent",
    "The Green Mile",
    "Furious 7",
    "Terminator 2: Judgment Day",
    "Exodus: Gods and Kings",
    "Harry Potter and the Goblet of Fire",
    "Cinderella",
    "The Revenant",
    "San Andreas",
    "How to Train Your Dragon 2",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "Ice Age",
    "Thor: The Dark World",
    "Man of Steel",
    "Harry Potter and the Half-Blood Prince",
    "I, Robot",
    "Gladiator",
    "The Wolf of Wall Street",
    "The Hobbit: The Desolation of Smaug",
    "The Jungle Book",
    "Skyfall",
    "Up",
    "Men in Black II",
    "The Bourne Legacy",
    "Suicide Squad",
    "The Adventures of Tintin",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "Monsters University",
    "Casino Royale",
    "Thor",
    "The Bourne Identity",
    "Allegiant",
    "Sin City: A Dame to Kill For",
    "Jupiter Ascending",
    "Ice Age: The Meltdown",
    "Kung Fu Panda",
    "Penguins of Madagascar",
    "Django Unchained",
    "Shutter Island",
    "World War Z",
    "Night at the Museum: Battle of the Smithsonian",
    "Sherlock Holmes: A Game of Shadows",
    "Divergent",
    "Harry Potter and the Prisoner of Azkaban",
    "Edge of Tomorrow",
    "Alice in Wonderland",
    "Star Trek Into Darkness",
    "Harry Potter and the Order of the Phoenix",
    "Mission: Impossible - Ghost Protocol",
    "Iron Man 3",
    "The Expendables",
    "Iron Man 2",
    "Snow White and the Huntsman",
    "Hercules",
    "Ocean's Twelve",
    "The Hunger Games: Catching Fire",
    "Saving Private Ryan",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Mission: Impossible",
    "Captain America: The First Avenger",
    "Cloud Atlas",
    "Wanted",
    "TRON: Legacy",
    "Star Trek",
    "Toy Story 2",
    "The Matrix Revolutions",
    "Inglourious Basterds",
    "Captain America: The Winter Soldier",
    "Terminator Salvation",
    "300: Rise of an Empire",
    "Now You See Me",
    "I Am Legend",
    "The Matrix Reloaded",
    "Ice Age: Dawn of the Dinosaurs",
    "Terminator 3: Rise of the Machines",
    "Prometheus",
    "Megamind",
    "Ted 2",
    "The Hateful Eight",
    "Apollo 13",
    "Oblivion",
    "Angels & Demons",
    "Mulan",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Elysium",
    "How to Train Your Dragon",
    "Troy",
    "RoboCop",
    "WALL·E",
    "Minority Report",
    "A Good Day to Die Hard",
    "Star Trek Beyond",
    "Ice Age: Continental Drift",
    "Battleship",
    "Watchmen",
    "Dracula Untold",
    "The Croods",
    "Seventh Son",
    "Home",
    "The Departed",
    "Warcraft",
    "Mission: Impossible III",
    "The Incredible Hulk",
    "The Italian Job",
    "Jason Bourne",
    "The Princess and the Frog",
    "Wreck-It Ralph",
    "Prince of Persia: The Sands of Time",
    "Rise of the Guardians",
    "Hotel Transylvania 2",
    "50 First Dates",
    "King Kong",
    "The Great Gatsby",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "The Expendables 3",
    "Ocean's Eleven",
    "Fantastic 4: Rise of the Silver Surfer",
    "Braveheart",
    "The Huntsman: Winter's War",
    "Independence Day",
    "The Curious Case of Benjamin Button",
    "Everest",
    "The Mummy: Tomb of the Dragon Emperor",
    "Toy Story 3",
    "GoldenEye",
    "Focus",
    "Olympus Has Fallen",
    "G.I. Joe: Retaliation",
    "A Beautiful Mind",
    "Batman Returns",
    "Transcendence",
    "National Treasure",
    "Starship Troopers",
    "Hellboy II: The Golden Army",
    "Armageddon",
    "Underworld: Awakening",
    "The Hangover Part II",
    "Superman Returns",
    "Sherlock Holmes",
    "The Terminal",
    "Cast Away",
    "Die Hard 2",
    "Dredd",
    "Lara Croft Tomb Raider: The Cradle of Life",
    "Hancock",
    "Kung Fu Panda 3",
    "Pacific Rim",
    "The Truman Show",
    "Alice Through the Looking Glass",
    "Hotel Transylvania",
    "Gods of Egypt",
    "Lilo & Stitch",
    "Contact",
    "Mission: Impossible II",
    "Need for Speed",
    "Die Another Day",
    "Star Wars: Episode I - The Phantom Menace",
    "The Chronicles of Narnia: Prince Caspian",
    "Charlie and the Chocolate Factory",
    "The Expendables 2",
    "The Bourne Supremacy",
    "Gone in Sixty Seconds",
    "Blood Diamond",
    "The Last Witch Hunter",
    "The Last Samurai",
    "Men in Black 3",
    "Zodiac",
    "Die Hard: With a Vengeance",
    "Green Lantern",
    "The Good Dinosaur",
    "Atlantis: The Lost Empire",
    "Now You See Me 2",
    "The Rock",
    "Life of Pi",
    "Kung Fu Panda 2",
    "Planet of the Apes",
    "The Emperor's New Groove",
    "In the Heart of the Sea",
    "Pompeii",
    "Dark Shadows",
    "Batman & Robin",
    "Cars 2",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Blade: Trinity",
    "Battle: Los Angeles",
    "Road to Perdition",
    "The Lone Ranger",
    "Live Free or Die Hard",
    "Salt",
    "Night at the Museum",
    "Independence Day: Resurgence",
    "The Man from U.N.C.L.E.",
    "Tangled",
    "War of the Worlds",
    "Les Misérables",
    "Batman Forever",
    "Mirror Mirror",
    "Madagascar",
    "Pan",
    "Stardust",
    "Chicken Little",
    "Clash of the Titans",
    "The Girl with the Dragon Tattoo",
    "The League of Extraordinary Gentlemen",
    "The Polar Express",
    "Shrek 2",
    "Shark Tale",
    "Oz: The Great and Powerful",
    "Eagle Eye",
    "The Simpsons Movie",
    "Ghost Rider",
    "Blackhat",
    "Cloudy with a Chance of Meatballs",
    "The Hunchback of Notre Dame",
    "xXx",
    "Rio",
    "Big Fish",
    "Gangs of New York",
    "Noah",
    "Face/Off",
    "Ender's Game",
    "The Angry Birds Movie",
    "The Aviator",
    "Grown Ups 2",
    "How the Grinch Stole Christmas",
    "The Bourne Ultimatum",
    "The Da Vinci Code",
    "Con Air",
    "Madagascar 3: Europe's Most Wanted",
    "The Holiday",
    "Wrath of the Titans",
    "Knight and Day",
    "Turbo",
    "Waterworld",
    "Mr. & Mrs. Smith",
    "Kingdom of Heaven",
    "Escape Plan",
    "Black Hawk Down",
    "RED 2",
    "The BFG",
    "Madagascar: Escape 2 Africa",
    "Star Wars: Episode III - Revenge of the Sith",
    "Mars Attacks!",
    "Shrek Forever After",
    "Star Wars: Episode II - Attack of the Clones",
    "John Carter",
    "The Monuments Men",
    "Due Date",
    "Jack the Giant Slayer",
    "The Secret Life of Walter Mitty",
    "Tropic Thunder",
    "Total Recall",
    "Unbroken",
    "The Golden Compass",
    "Shrek the Third",
    "AVP: Alien vs. Predator",
    "Tomorrow Never Dies",
    "2 Guns",
    "After Earth",
    "The Legend of Tarzan",
    "Death Race",
    "Perfume: The Story of a Murderer",
    "Rio 2",
    "American Gangster",
    "Ocean's Thirteen",
    "Unbreakable",
    "The Day the Earth Stood Still",
    "The Mummy Returns",
    "Bolt",
    "47 Ronin",
    "Spirit: Stallion of the Cimarron",
    "Antz",
    "Lara Croft: Tomb Raider",
    "The Tourist",
    "The Day After Tomorrow",
    "Enemy at the Gates",
    "Cloudy with a Chance of Meatballs 2",
    "Enemy of the State",
    "Click",
    "Wild Wild West",
    "Journey 2: The Mysterious Island",
    "The Taking of Pelham 1 2 3",
    "You Don't Mess with the Zohan",
    "Percy Jackson: Sea of Monsters",
    "Charlie's Angels",
    "The Brothers Grimm",
    "Austin Powers in Goldmember",
    "Teenage Mutant Ninja Turtles: Out of the Shadows",
    "A Christmas Carol",
    "The World Is Not Enough",
    "R.I.P.D.",
    "Sucker Punch",
    "Alexander",
    "White House Down",
    "This Means War",
    "Treasure Planet",
    "Scott Pilgrim vs. the World",
    "Grown Ups",
    "Valkyrie",
    "Mr. Peabody & Sherman",
    "True Lies",
    "Abraham Lincoln: Vampire Hunter",
    "Fantastic Four",
    "Bad Boys II",
    "Immortals",
    "Unstoppable",
    "The Island",
    "Robin Hood",
    "Body of Lies",
    "Legend of the Guardians: The Owls of Ga'Hoole",
    "Happy Feet",
    "Real Steel",
    "The Road to El Dorado",
    "Just Go with It",
    "Master and Commander: The Far Side of the World",
    "The SpongeBob Movie: Sponge Out of Water",
    "Swordfish",
    "Tower Heist",
    "Epic",
    "Surrogates",
    "The Smurfs",
    "The Three Musketeers",
    "Air Force One",
    "Monster House",
    "Over the Hedge",
    "Lincoln",
    "Monsters vs Aliens",
    "Space Jam",
    "Meet Joe Black",
    "Rush Hour 2",
    "Beowulf",
    "The Sorcerer's Apprentice",
    "Children of Men",
    "The Little Prince",
    "Spider-Man 2",
    "Hulk",
    "Safe House",
    "The Peanuts Movie",
    "Pearl Harbor",
    "Deep Impact",
    "S.W.A.T.",
    "A.I. Artificial Intelligence",
    "The Last Airbender",
    "Public Enemies",
    "Hook",
    "Charlie's Angels: Full Throttle",
    "Point Break",
    "Annie",
    "G.I. Joe: The Rise of Cobra",
    "Meet the Fockers",
    "The Smurfs 2",
    "Little Fockers",
    "The Book of Eli",
    "Hugo",
    "Catwoman",
    "Jarhead",
    "Twister",
    "Last Action Hero",
    "Conan the Barbarian",
    "Wild Hogs",
    "The Green Hornet",
    "Where the Wild Things Are",
    "The Secret Life of Pets",
    "Scooby-Doo",
    "What Women Want",
    "The Dictator",
    "I, Frankenstein",
    "Hairspray",
    "The Mask of Zorro",
    "The Legend of Zorro",
    "Marley & Me",
    "Eragon",
    "Stuart Little",
    "Green Zone",
    "Rango",
    "Ben-Hur",
    "Robots",
    "War Horse",
    "Killer Elite",
    "The Prince of Egypt",
    "Alvin and the Chipmunks: The Squeakquel",
    "Bee Movie",
    "Doom",
    "The Lovely Bones",
    "Enchanted",
    "The Core",
    "Munich",
    "Signs",
    "Australia",
    "Eat Pray Love",
    "Elektra",
    "You've Got Mail",
    "Transformers: Dark of the Moon",
    "The Finest Hours",
    "Hollow Man",
    "Stuart Little 2",
    "Eyes Wide Shut",
    "Alvin and the Chipmunks: The Road Chip",
    "The Chronicles of Riddick",
    "The Village",
    "Zookeeper",
    "Vanilla Sky",
    "The 13th Warrior",
    "Spy Game",
    "Hall Pass",
    "Arthur and the Invisibles",
    "Evan Almighty",
    "Tears of the Sun",
    "Dreamcatcher",
    "G-Force",
    "Couples Retreat",
    "Open Season",
    "Dinosaur",
    "Cliffhanger"
  ],
  "Video Games": [
    "Minecraft",
    "Fortnite",
    "Mario Kart",
    "Pokémon",
    "Valorant",
    "Roblox",
    "The Sims",
    "Among Us",
    "Grand Theft Auto",
    "Call of Duty",
    "Super Mario",
    "The Legend of Zelda",
    "Overwatch",
    "Rocket League",
    "Fall Guys",
    "Animal Crossing",
    "Clash of Clans",
    "Apex Legends",
    "Terraria",
    "Wii Sports",
    "League of Legends",
    "Marvel Rivals",
    "Mortal Kombat",
    "Street Fighter",
    "Candy Crush",
    "Plants vs. Zombies",
    "Red Dead Redemption",
    "Halo",
    "Sonic the Hedgehog",
    "Five Nights at Freddy's",
    "Super Mario Bros.",
    "Mario Kart Wii",
    "Wii Sports Resort",
    "Pokemon Red/Pokemon Blue",
    "Tetris",
    "New Super Mario Bros.",
    "Wii Play",
    "New Super Mario Bros. Wii",
    "Duck Hunt",
    "Nintendogs",
    "Mario Kart DS",
    "Pokemon Gold/Pokemon Silver",
    "Wii Fit",
    "Wii Fit Plus",
    "Kinect Adventures!",
    "Grand Theft Auto V",
    "Grand Theft Auto: San Andreas",
    "Super Mario World",
    "Brain Age: Train Your Brain in Minutes a Day",
    "Pokemon Diamond/Pokemon Pearl",
    "Super Mario Land",
    "Super Mario Bros. 3",
    "Grand Theft Auto: Vice City",
    "Pokemon Ruby/Pokemon Sapphire",
    "Pokemon Black/Pokemon White",
    "Brain Age 2: More Training in Minutes a Day",
    "Gran Turismo 3: A-Spec",
    "Call of Duty: Modern Warfare 3",
    "Pokémon Yellow: Special Pikachu Edition",
    "Call of Duty: Black Ops",
    "Pokemon X/Pokemon Y",
    "Call of Duty: Black Ops 3",
    "Call of Duty: Black Ops II",
    "Call of Duty: Modern Warfare 2",
    "Grand Theft Auto III",
    "Super Smash Bros. Brawl",
    "Animal Crossing: Wild World",
    "Mario Kart 7",
    "Halo 3",
    "Pokemon HeartGold/Pokemon SoulSilver",
    "Super Mario 64",
    "Gran Turismo 4",
    "Super Mario Galaxy",
    "Pokemon Omega Ruby/Pokemon Alpha Sapphire",
    "Super Mario Land 2: 6 Golden Coins",
    "Grand Theft Auto IV",
    "Gran Turismo",
    "Super Mario 3D Land",
    "Gran Turismo 5",
    "Super Mario All-Stars",
    "Pokemon FireRed/Pokemon LeafGreen",
    "Just Dance 3",
    "Call of Duty: Ghosts",
    "Halo: Reach",
    "Mario Kart 64",
    "New Super Mario Bros. 2",
    "Halo 4",
    "Final Fantasy VII",
    "Just Dance 2",
    "Gran Turismo 2",
    "Call of Duty 4: Modern Warfare",
    "Donkey Kong Country",
    "Animal Crossing: New Leaf",
    "Mario Party DS",
    "The Elder Scrolls V: Skyrim",
    "Super Mario Kart",
    "Halo 2",
    "Wii Party",
    "FIFA 16",
    "Mario Party 8",
    "Pokemon Black 2/Pokemon White 2",
    "FIFA Soccer 13",
    "The Sims 3",
    "GoldenEye 007",
    "Mario & Sonic at the Olympic Games",
    "Final Fantasy X",
    "Final Fantasy VIII",
    "Pokémon Platinum Version",
    "Pac-Man",
    "Grand Theft Auto: Liberty City Stories",
    "Super Mario Galaxy 2",
    "Star Wars Battlefront (2015)",
    "The Legend of Zelda: Ocarina of Time",
    "Call of Duty: Advanced Warfare",
    "Crash Bandicoot 2: Cortex Strikes Back",
    "Super Mario Bros. 2",
    "Super Smash Bros. for Wii U and 3DS",
    "Call of Duty: World at War",
    "Battlefield 3",
    "The Legend of Zelda: Twilight Princess",
    "Just Dance",
    "Need for Speed Underground",
    "Tekken 3",
    "Crash Bandicoot 3: Warped",
    "Super Smash Bros. Melee",
    "Mario Kart 8",
    "Fallout 4",
    "Mario Kart: Double Dash!!",
    "Just Dance 4",
    "Need for Speed Underground 2",
    "FIFA 14",
    "Medal of Honor: Frontline",
    "Uncharted 3: Drake's Deception",
    "Crash Bandicoot",
    "Zumba Fitness",
    "Gears of War 2",
    "Uncharted 2: Among Thieves",
    "FIFA 12",
    "Big Brain Academy",
    "Donkey Kong Country Returns",
    "FIFA 15",
    "Assassin's Creed III",
    "Halo: Combat Evolved",
    "Pokémon Emerald Version",
    "Kingdom Hearts",
    "Pokémon Crystal Version",
    "Halo 3: ODST",
    "Super Mario Sunshine",
    "Street Fighter II: The World Warrior",
    "World of Warcraft",
    "Driver",
    "Kinect Sports",
    "Gears of War 3",
    "Gears of War",
    "Metal Gear Solid 2: Sons of Liberty",
    "Sonic the Hedgehog 2",
    "Metal Gear Solid",
    "Metal Gear Solid 4: Guns of the Patriots",
    "The Last of Us",
    "Final Fantasy XII",
    "LittleBigPlanet",
    "Dragon Quest IX: Sentinels of the Starry Skies",
    "LEGO Star Wars: The Complete Saga",
    "Resident Evil 2",
    "Tekken 2",
    "Cooking Mama",
    "Destiny",
    "Assassin's Creed II",
    "Super Smash Bros.",
    "Assassin's Creed",
    "Batman: Arkham City",
    "Forza Motorsport 3",
    "Monster Hunter Freedom Unite",
    "Super Mario Advance",
    "Mario Kart: Super Circuit",
    "Pokemon Stadium",
    "Crash Bandicoot: The Wrath of Cortex",
    "Final Fantasy XIII",
    "Dr. Mario",
    "Pokemon Pinball",
    "Final Fantasy IX",
    "Final Fantasy X-2",
    "Donkey Kong 64",
    "Professor Layton and the Curious Village",
    "Tomb Raider II",
    "Madden NFL 2004",
    "Dragon Quest VIII: Journey of the Cursed King",
    "Diablo III",
    "Super Mario Land 3: Wario Land",
    "New Super Mario Bros. U",
    "The Legend of Zelda: Phantom Hourglass",
    "Donkey Kong Country 2: Diddy's Kong Quest",
    "Tomodachi Life",
    "Kirby's Dream Land",
    "Medal of Honor: Rising Sun",
    "Fable III",
    "Microsoft Flight Simulator",
    "Guitar Hero II",
    "Resident Evil 5",
    "Grand Theft Auto: Vice City Stories",
    "FIFA Soccer 11",
    "Resident Evil",
    "Tony Hawk's Pro Skater",
    "Warzone 2100",
    "Spyro the Dragon",
    "Link's Crossbow Training",
    "Guitar Hero III: Legends of Rock",
    "Pokemon Mystery Dungeon: Explorers of Time/Explorers of Darkness",
    "Fallout 3",
    "Uncharted: Drake's Fortune",
    "Madden NFL 06",
    "Diddy Kong Racing",
    "Monster Hunter Freedom 3",
    "God of War III",
    "StarCraft II: Wings of Liberty",
    "Crash Team Racing",
    "FIFA 17",
    "Driver 2",
    "The Simpsons: Hit & Run",
    "Tony Hawk's Pro Skater 2",
    "Animal Crossing: City Folk",
    "The Lord of the Rings: The Two Towers",
    "Forza Motorsport 4",
    "Tomb Raider",
    "The Legend of Zelda: A Link to the Past",
    "The Legend of Zelda: The Wind Waker",
    "Mario & Sonic at the Olympic Winter Games",
    "Luigi's Mansion: Dark Moon",
    "Splatoon",
    "Madden NFL 2005",
    "Pitfall!",
    "Madden NFL 07",
    "Spider-Man: The Movie",
    "Dragon Quest VII: Warriors of Eden",
    "Uncharted: The Nathan Drake Collection",
    "God of War",
    "Nintendo Land",
    "Michael Jackson: The Experience",
    "Tony Hawk's Pro Skater 3",
    "Winning Eleven: Pro Evolution Soccer 2007",
    "The Elder Scrolls IV: Oblivion",
    "Zelda II: The Adventure of Link",
    "Need for Speed: Most Wanted",
    "Resistance: Fall of Man",
    "Kingdom Hearts II",
    "Asteroids",
    "Fable II",
    "Halo 5: Guardians",
    "Batman: Arkham Asylum",
    "Super Mario 3D World",
    "Namco Museum",
    "Assassin's Creed: Revelations",
    "Metal Gear Solid 3: Snake Eater",
    "Daxter",
    "Warcraft II: Tides of Darkness",
    "FIFA Soccer 06",
    "EyeToy Play",
    "Gran Turismo 5 Prologue",
    "Uncharted 4: A Thief's End",
    "Street Fighter IV",
    "Teenage Mutant Ninja Turtles",
    "Excitebike",
    "Frogger",
    "Madden NFL 2003",
    "Watch Dogs",
    "Super Mario World 2: Yoshi's Island",
    "Half-Life",
    "FIFA Soccer 07",
    "Street Fighter II Turbo",
    "Carnival Games",
    "The Legend of Zelda: Skyward Sword",
    "World of Warcraft: The Burning Crusade",
    "Fallout: New Vegas",
    "God of War II",
    "World Soccer Winning Eleven 9",
    "Forza Motorsport 2",
    "Namco Museum Vol.3",
    "Tekken Tag Tournament",
    "Star Fox 64",
    "Far Cry 4",
    "Golf",
    "Professor Layton and the Diabolical Box",
    "Left 4 Dead 2",
    "Namco Museum: 50th Anniversary",
    "EA Sports Active",
    "Assassin's Creed: Unity",
    "Donkey Kong Land",
    "Tony Hawk's Underground",
    "Assassin's Creed IV: Black Flag",
    "Monster Hunter 4 Ultimate",
    "MotorStorm",
    "Dragon Warrior III",
    "Tekken 5",
    "Sports Champions",
    "World Soccer Winning Eleven 8 International",
    "NBA 2K16",
    "Namco Museum Vol.1",
    "Flash Focus: Vision Training in Minutes a Day",
    "The Legend of Zelda: Link's Awakening",
    "Mario & Luigi: Bowser's Inside Story",
    "Big Brain Academy: Wii Degree",
    "Nintendogs + cats",
    "Batman: Arkham Knight",
    "LEGO Indiana Jones: The Original Adventures",
    "Mario & Sonic at the London 2012 Olympic Games",
    "Resident Evil Director's Cut",
    "Ratchet & Clank: Size Matters",
    "The Sims: Unleashed",
    "Super Paper Mario",
    "Just Dance 2014",
    "Harry Potter and the Sorcerer's Stone",
    "The Witcher 3: Wild Hunt",
    "Resident Evil 3: Nemesis",
    "Spyro: Year of the Dragon",
    "Pokémon Trading Card Game",
    "FIFA Soccer 2005",
    "MySims",
    "Battlefield 4",
    "Tony Hawk's Pro Skater 4",
    "Friend Collection",
    "Midnight Club 3: DUB Edition",
    "Banjo-Kazooie",
    "SOCOM: U.S. Navy SEALs",
    "Guitar Hero: World Tour",
    "Jak and Daxter: The Precursor Legacy",
    "Gran Turismo 6",
    "Pokemon Snap",
    "Pro Evolution Soccer 2008",
    "FIFA Soccer 10",
    "Resident Evil 4",
    "Doom II: Hell on Earth",
    "The Simpsons: Road Rage",
    "Star Wars: Battlefront",
    "Cooking Mama 2: Dinner With Friends",
    "Tom Clancy's The Division",
    "Luigi's Mansion",
    "Star Wars: Battlefront II",
    "WWF SmackDown!",
    "Croc: Legend of the Gobbos",
    "Tomb Raider III: Adventures of Lara Croft",
    "The Getaway",
    "James Bond 007: Agent Under Fire",
    "LEGO Star Wars: The Video Game",
    "Spyro 2: Ripto's Rage!",
    "Rugrats in Paris: The Movie",
    "Left 4 Dead",
    "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
    "Kung Fu",
    "Clubhouse Games",
    "Assassin's Creed: Brotherhood",
    "FIFA Soccer 2004",
    "Guitar Hero: On Tour",
    "Battlefield: Bad Company 2",
    "Far Cry 3",
    "Tekken 4",
    "Borderlands",
    "Monster Hunter 4",
    "Final Fantasy III",
    "Grand Theft Auto 2",
    "LittleBigPlanet 2",
    "F-1 Race",
    "Spider-Man 2",
    "FIFA Soccer 2003",
    "Crash Bash",
    "LEGO Batman: The Videogame",
    "The Legend of Zelda: Spirit Tracks",
    "Metal Gear Solid V: The Phantom Pain",
    "WWF War Zone",
    "The Legend of Zelda: Majora's Mask",
    "Professor Layton and the Unwound Future",
    "Rugrats: Search For Reptar",
    "James Bond 007: Nightfire",
    "Ratchet & Clank",
    "English Training: Have Fun Improving Your Skills!",
    "Star Wars Episode III: Revenge of the Sith",
    "Mario Party 9",
    "Max Payne",
    "The Lord of the Rings: The Return of the King",
    "Assassin's Creed Syndicate",
    "True Crime: Streets of LA",
    "Wii Music",
    "Gran Turismo (PSP)",
    "Monster Hunter X",
    "Tekken",
    "L.A. Noire",
    "Yokai Watch 2 Ganso/Honke",
    "Madden NFL 16",
    "007: Tomorrow Never Dies",
    "Baseball",
    "Killer Instinct",
    "WWF SmackDown! 2: Know Your Role",
    "Dragon Quest VI: Maboroshi no Daichi",
    "Crisis Core: Final Fantasy VII",
    "God of War: Chains of Olympus",
    "Dance Central",
    "Enter the Matrix",
    "Super Mario Maker",
    "Ace Combat 04: Shattered Skies",
    "Rhythm Heaven",
    "Club Penguin: Elite Penguin Force",
    "Sonic Rush",
    "Resident Evil 6",
    "Halo: The Master Chief Collection",
    "FIFA Soccer 08",
    "Spider-Man",
    "Dragon Warrior IV",
    "Need for Speed III: Hot Pursuit",
    "Star Wars Episode I Racer",
    "Personal Trainer: Cooking",
    "Heavy Rain",
    "Mass Effect 2",
    "Dragon Ball Z: Budokai",
    "World Class Track Meet",
    "Madden NFL 2002",
    "Donkey Kong",
    "The Sims: Vacation",
    "Mass Effect 3",
    "Borderlands 2",
    "The Legend of Zelda: A Link Between Worlds",
    "Kung Fu Panda",
    "Epic Mickey",
    "Rayman",
    "Saints Row 2",
    "Mike Tyson's Punch-Out!!",
    "WWE SmackDown! Shut Your Mouth",
    "Tom Clancy's Splinter Cell",
    "Killzone 2",
    "Dragon Ball Z: Budokai Tenkaichi 3",
    "NBA 2K13",
    "Gears of War: Ultimate Edition",
    "Star Fox",
    "The Sims: Livin Large",
    "Devil May Cry",
    "World Soccer Winning Eleven 6 International",
    "Middle-Earth: Shadow of Mordor",
    "Animal Crossing: Happy Home Designer",
    "Star Wars: The Old Republic",
    "The Sims 4",
    "Hitman 2: Silent Assassin",
    "Sonic Heroes",
    "Kirby Super Star Ultra",
    "Wave Race 64",
    "Pac-Man Collection",
    "SOCOM II: U.S. Navy SEALs",
    "WWE SmackDown! vs. RAW 2006",
    "inFAMOUS",
    "Mass Effect",
    "WarioWare: Smooth Moves",
    "Cooking Mama: Cook Off",
    "World Soccer Winning Eleven 7 International",
    "Sonic Mega Collection Plus",
    "Sega Superstars Tennis",
    "Titanfall",
    "Hot Shots Golf 3",
    "Call of Duty: Finest Hour",
    "Syphon Filter",
    "Imagine: Babyz",
    "Zumba Fitness 2",
    "Colin McRae Rally",
    "The Elder Scrolls III: Morrowind",
    "Madden NFL 13",
    "F-Zero",
    "Command & Conquer: Red Alert",
    "Yoshi's Story",
    "Skylanders: Spyro's Adventure",
    "WWE SmackDown! vs. Raw",
    "BioShock",
    "Madden NFL 10",
    "Medal of Honor",
    "Metroid Prime",
    "Finding Nemo",
    "Myst",
    "Imagine: Fashion Designer",
    "Need for Speed: Hot Pursuit",
    "WWE SmackDown! Here Comes the Pain",
    "Yoshi's Island DS",
    "Star Wars: The Force Unleashed",
    "Dragon Quest V: Tenkuu no Hanayome",
    "Mortal Kombat Trilogy",
    "Hot Shots Golf",
    "A Bug's Life",
    "NBA Street",
    "WWF SmackDown! Just Bring It",
    "Professor Layton and the Last Specter",
    "Monster Hunter Tri",
    "Killzone 3",
    "Jak II",
    "Ratchet & Clank: Going Commando",
    "Tekken 6",
    "inFAMOUS: Second Son",
    "Sonic and the Secret Rings",
    "Saints Row: The Third",
    "Missile Command",
    "Mario Paint",
    "Metroid",
    "Pokémon Stadium 2",
    "Call of Duty 3",
    "Mario Party",
    "Onimusha: Warlords",
    "Mortal Kombat X"
  ],
  "Marvel": [
    "Spider-Man",
    "Iron Man",
    "Thor",
    "Hulk",
    "Black Widow",
    "Hawkeye",
    "Captain America",
    "Black Panther",
    "Doctor Strange",
    "Scarlet Witch",
    "Vision",
    "Thanos",
    "Loki",
    "Deadpool",
    "Wolverine",
    "Storm",
    "Cyclops",
    "Jean Grey",
    "Magneto",
    "Professor X",
    "Daredevil",
    "Moon Knight",
    "Ant-Man",
    "The Wasp",
    "Star-Lord",
    "Groot",
    "Rocket Raccoon",
    "Gamora",
    "Nebula",
    "Venom",
    "A Friend",
    "A La Mode",
    "A'di",
    "A'ishah",
    "A'Kane",
    "A'Kurru U'mbaya",
    "A'Lars",
    "A'Lars II",
    "A'Sai",
    "A'yin",
    "A-1 Sauce",
    "A-14",
    "A-Bomb (Warp World)",
    "A-Tuna",
    "A-Wet-man",
    "A. Summers",
    "A. Trabbold",
    "A. Verni",
    "A.C. Bradley",
    "A.C. O'Connor",
    "A.D. Doug",
    "A.G. Bell",
    "A.I. Sarah (Model 00-1468)",
    "A.J Dohertz",
    "A.J. (Backdoor Boys)",
    "A.J.",
    "A.J. Patton",
    "A.P.E.",
    "A3",
    "Aa-Gorn",
    "Aa-Thak",
    "Aadam",
    "Aaf Capmi Piap",
    "Aahi",
    "Aahmes",
    "Aaidan Blomfield",
    "Aala (Deity)",
    "Aala (Taa-an)",
    "Aalbort",
    "Aali",
    "Aaliyah Hardin",
    "Aamir",
    "Aamir Khan",
    "Aamshed",
    "Aan Taanu",
    "Aard",
    "Aardvark",
    "Aardwolf (Hyena Clan)",
    "Aarkus",
    "Aaron (Reporter)",
    "Aaron (Student)",
    "Aaron Aikman",
    "Aaron Alexander",
    "Aaron Amberson",
    "Aaron Carpenter",
    "Aaron Cashin",
    "Aaron Chord",
    "Aaron Davis",
    "Aaron Delgato",
    "Aaron Downing",
    "Aaron English",
    "Aaron Fischer",
    "Aaron Fox",
    "Aaron Heller",
    "Aaron Isaacs",
    "Aaron James",
    "Aaron Kearse",
    "Aaron Lopresti",
    "Aaron MacKenzie",
    "Aaron Nicholson",
    "Aaron Reece",
    "Aaron Rosenberg",
    "Aaron Salomon",
    "Aaron Schmidt",
    "Aaron Soames",
    "Aaron Sokoto",
    "Aaron Spiro",
    "Aaron Stack",
    "Aaron Stack (Impostor)",
    "Aaron Stankey",
    "Aaron the Aakon",
    "Aaron the Sorcerer",
    "Aaron Thorne",
    "Aaron Verne",
    "Aaron Warren",
    "Ab Waltin",
    "Abadon",
    "Abahla",
    "Aban",
    "Abarac",
    "Abbadona (Angel)",
    "Abbadona Hellgore",
    "Abbas",
    "Abbas al-Abbad",
    "Abbess Horror",
    "Abbey Sykes",
    "Abbot",
    "Abbot (U.S. Army)",
    "Abbot Shamescuttle",
    "Abbott",
    "Abby Davis",
    "Abby Levine",
    "Abby Miller",
    "Abby Morris",
    "Abby Rubin",
    "Abby-L",
    "Abd-el-Hazred",
    "Abdallah El-Faouly",
    "Abdi",
    "Abdol",
    "Abdomina",
    "Abdul",
    "Abdul Abismah",
    "Abdul Al-Rahman",
    "Abdul Ben Hassi",
    "Abdul Faoul",
    "Abdul Hurani",
    "Abdul Muhammed",
    "Abdul Qamar",
    "Abdul T'Chaka Rosenthal",
    "Abdul Tallosh",
    "Abdul Zu Fadh",
    "Abe Benerstein",
    "Abe Hargreaves",
    "Abe Jankovitz",
    "Abel",
    "Abel Barlow",
    "Abel Stack",
    "Abel Tennison",
    "Abelard",
    "Abelisk",
    "Abena",
    "Abena Adebayo",
    "Abeni",
    "Abeni (Mutant)",
    "Abercombie",
    "Aberdeen Angus",
    "Abib",
    "Abigail (Hollywood Hills Middle School)",
    "Abigail (Mutant)",
    "Abigail Arcane",
    "Abigail Baxter",
    "Abigail Boylen",
    "Abigail Brand",
    "Abigail Brown",
    "Abigail Burns",
    "Abigail Callaghan",
    "Abigail Colt",
    "Abigail Cowan",
    "Abigail Dunton",
    "Abigail Harkness",
    "Abigail Housman",
    "Abigail Jarvis",
    "Abigail Marigold",
    "Abigail Mercury (Clone)",
    "Abigail Mercury",
    "Abigail Slade",
    "Abigail Stewart",
    "Abigail Thanriaguiaxus",
    "Abigail Tyler",
    "Abigail Varden",
    "Abigail Verpoorten",
    "Abigail Whistler",
    "Abigail Williams",
    "Abigail Wright",
    "Abigor",
    "Abilash Tandon",
    "Abilene Cashman",
    "Abira",
    "Able Baker",
    "Able Doone",
    "Abner Abernaphy",
    "Abner Abernathy",
    "Abner Brody",
    "Abner Croit",
    "Abner Doolittle",
    "Abner Dunson",
    "Abner Ferris",
    "Abner Jenkins",
    "Abner Jonas",
    "Abner Little",
    "Abner Moorehead",
    "Abner Perkins",
    "Abner Perry",
    "Abominable Snowman (Howling Commandos)",
    "Abomination",
    "Abomination (Mojomedia)",
    "Abomination (Morlock)",
    "Abominite",
    "Abra and Cadabra",
    "Abraham",
    "Abraham Adamson",
    "Abraham Beame",
    "Abraham Brown",
    "Abraham Cabot",
    "Abraham Cornelius",
    "Abraham Donovan",
    "Abraham Erskine",
    "Abraham James",
    "Abraham Kieros",
    "Abraham Klein",
    "Abraham Lincoln (A.I.)",
    "Abraham Lincoln (Android)",
    "Abraham Lincoln",
    "Abraham Shoenstein",
    "Abraham Shooter",
    "Abraham Stoker",
    "Abraham Van Brunt",
    "Abraham van Helsing",
    "Abraham Verne",
    "Abraham Walker",
    "Abraham Whistler",
    "Abraham Wilson (Heroes Reborn)",
    "Abraham Zimmer",
    "Abraham Zimmer Jr.",
    "Abram",
    "Abrams (A.I.M.)",
    "Abraxas",
    "Abrogate",
    "Abscissa",
    "Absent-Minded Mac",
    "Absolon Mercator",
    "Absolute Sea Carnage",
    "Absorbing Bug",
    "Absorbing Man (Mojomedia)",
    "Absorbing Mouse",
    "Abstract",
    "Absynthe",
    "Absyrtus",
    "Abu Bakaar",
    "Abu Ben Hakim",
    "Abu Dakir",
    "Abu Ho Dadi",
    "Abu Mussan",
    "Abu Mūsā Jābir ibn Hayyān al-Azdi",
    "Abu-Ben Ar",
    "Abu-Jamal Rodriguez",
    "Abwama",
    "Abyss (Cosmic Sorcerer)",
    "Abyss",
    "Abyss (Entity)",
    "Abysss",
    "AC and DC",
    "AC-DC",
    "Acari",
    "Acba",
    "Accolon",
    "Ace",
    "Ace (G.R.A.M.P.A.)",
    "Ace (Pilot)",
    "Ace (S.H.I.E.L.D.)",
    "Ace Arnold",
    "Ace Fenton",
    "Ace Frehley",
    "Ace Maxwell",
    "Ace Peterson",
    "Ace Robinson",
    "Ace Spencer",
    "Ace Taggert",
    "Ace Turmbull",
    "Aces Wilde",
    "Achak",
    "Achebe",
    "Achelous",
    "Achille DiBacco",
    "Achilles",
    "Achilles (Helmut)",
    "Achlemedes",
    "Achmar",
    "Achmed Al-Khalad",
    "Achmed Al-Khalad (Heroes Reborn)",
    "Achmed El Gibár",
    "Achmed Korba",
    "Acid Queen",
    "Acidroid",
    "Acitua",
    "Acorn Annie",
    "Acrallidus",
    "Acrobat (1940s)",
    "Acrobat (Spider-Squad)",
    "Acroyear",
    "Active-Radio Spider",
    "Actor (Greek)",
    "Actor (Spy)",
    "Aculdi",
    "Ada",
    "Ada (Techno Sorceress)",
    "Ada Flores",
    "Adad",
    "Adahm",
    "Adai",
    "Adalbert Kamentin",
    "Adam",
    "Adam (Gideon)",
    "Adam (Mutant)",
    "Adam (Weapon VI Upgrade)",
    "Adam 3,031",
    "Adam Able",
    "Adam Austin",
    "Adam Aziz",
    "Adam Bentley",
    "Adam Berman",
    "Adam Blackveil",
    "Adam Brashear",
    "Adam Brigman",
    "Adam Carter",
    "Adam Casim",
    "Adam Clayton",
    "Adam Cooper",
    "Adam Cross",
    "Adam Crown",
    "Adam Del Re",
    "Adam Destine",
    "Adam Essex",
    "Adam Fisher",
    "Adam Frost",
    "Adam Gree",
    "Adam Gulliver",
    "Adam Harkins",
    "Adam Henderson",
    "Adam Hitt",
    "Adam II",
    "Adam Ishima",
    "Adam Jay",
    "Adam K'ad-Mon",
    "Adam Kane",
    "Adam Kipiniak",
    "Adam Kubert",
    "Adam Mann",
    "Adam Manna",
    "Adam Neramani",
    "Adam Neushuk",
    "Adam Peters",
    "Adam Pratt",
    "Adam Roderick",
    "Adam Rodney",
    "Adam Rossi",
    "Adam Rykland",
    "Adam Shockley",
    "Adam Simon",
    "Adam Spectre",
    "Adam Stokes",
    "Adam Torchia",
    "Adam Ware",
    "Adam Warlock",
    "Adam Warlox",
    "Adam Wright",
    "Adam Y",
    "Adam-X (Adorable X-Babies)",
    "Adamantine",
    "Adamo Dioli",
    "Adams (EET)",
    "Adams (Stark Industries)",
    "Adani",
    "Adanna",
    "Adanna Gui",
    "Addison Blackburn",
    "Addison Falk",
    "Addy Brock",
    "Adelbert Greywing",
    "Adele Gorton",
    "Adele Hawthorne",
    "Adele Racine",
    "Adele Santiago",
    "Adelicia von Krupp",
    "Adena",
    "Adept (Claw Sect)",
    "Adewale Ekoku",
    "Adhira Deol",
    "Adi (65,000,000 BC)",
    "Adimu Chiume",
    "Adina Johnson",
    "Adina Malcolm",
    "Adjudicator",
    "Adjunct",
    "Adlai Schmidt",
    "Administrator",
    "Administrator Porus",
    "Administrator Umbridge",
    "Admiral (Xandarian)",
    "Admiral Footsu",
    "Admiral Fukyama",
    "Admiral Jolnes",
    "Admiral Kiefer",
    "Admiral Nippo",
    "Admiral Nodope",
    "Admiral Perkins",
    "Admiral von Roeder",
    "Admiral White",
    "Adolf Hitler",
    "Adolf Hitler (Warp World)",
    "Adolf Impossible",
    "Adolfo Costa",
    "Adolfus Crane",
    "Adolphe Hiccup",
    "Adolphus",
    "Adolphus Williamson",
    "Adoma",
    "Adomox",
    "Adonai",
    "Adonis",
    "Adora",
    "Adoro",
    "Adramaelec",
    "Adri Nital",
    "Adria",
    "Adria Lafayette",
    "Adria Wagner",
    "Adrian (Cat)",
    "Adrian Castorp",
    "Adrian Chase",
    "Adrian Corbo",
    "Adrian Defoe",
    "Adrian Eiskalt",
    "Adrian Gray",
    "Adrian J. Watts",
    "Adrian Loring",
    "Adrian Luca",
    "Adrian Lynn",
    "Adrian Mortte",
    "Adrian Sammish",
    "Adrian Toomes (Doppelganger)",
    "Adrian Toomes",
    "Adrian Toomes (Noir)",
    "Adrian Toomes (Young)",
    "Adrian Turner",
    "Adrian Warsame",
    "Adriana Soria",
    "Adrianne Brown",
    "Adrianne Palicki",
    "Adriano Tumino",
    "Adriel",
    "Adrienne",
    "Adrienne Bowen",
    "Adrienne Brashear",
    "Adrienne Dore",
    "Adrienne Frost",
    "Adrienne Hatros",
    "Adron",
    "Adu Bey",
    "Adula",
    "Adulaysha",
    "Adur",
    "Adva",
    "Advanced Idea Mechanics (Tsum Tsum)",
    "Adversary",
    "Advisor",
    "Adwoma",
    "Aegeus",
    "Aegialues",
    "Aegir",
    "Aegis (Monster)",
    "Aegis (Proemial God)",
    "Aegisthus",
    "Aegle",
    "Aeish",
    "Ael-Dan",
    "Ael-Dann",
    "Aelfric",
    "Aelfyre Whitemane",
    "Aelfyre Whitemane (Warp World)",
    "Aelsa Featherwine of the Fay",
    "Aeltri",
    "Aeneas",
    "Aenetus",
    "Aentaros",
    "Aeon",
    "Aer",
    "Aera",
    "Aeric"
  ],
  "Disney": [
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Cinderella",
    "Snow White",
    "Ariel",
    "Belle",
    "Aladdin",
    "Jasmine",
    "Simba",
    "Mufasa",
    "Elsa",
    "Anna",
    "Olaf",
    "Moana",
    "Maui",
    "Stitch",
    "Peter Pan",
    "Tinker Bell",
    "Buzz Lightyear",
    "Woody",
    "Lightning McQueen",
    "Nemo",
    "Dory",
    "Winnie the Pooh",
    "Tigger",
    "Rapunzel",
    "Cruella de Vil",
    "Maleficent",
    "Abigail the Cow",
    "Acer",
    "Abu",
    "Adolphus",
    "Accordion Owl",
    "Agent Heeley",
    "Achilles",
    "Alan Ripple",
    "Prince Achmed",
    "Alebrijes",
    "Aconcagua",
    "Alex (Float)",
    "Agent",
    "Alexander Hugo",
    "King Agnarr",
    "Chet Alexander",
    "Agnes De'Snake",
    "Alpha",
    "Agustín Madrigal",
    "Ambassador Auva",
    "Akela",
    "Ambassador Mira",
    "Aladar",
    "Ambassador Naos",
    "Aladar's Mother",
    "Amphibian King",
    "Anchor",
    "Alan-A-Dale",
    "The Ancient King",
    "Albertosaurus",
    "Mr. Andersen's Emotions",
    "Alice",
    "Mr. Andersen",
    "Alice Doe",
    "Mrs. Andersen",
    "Alice's Sister",
    "Bonnie Anderson",
    "Aliens (Chicken Little)",
    "Duncan P. Anderson",
    "Alley Cats",
    "Mrs. Anderson",
    "Alley Dogs",
    "Mr. Anderson",
    "Alligators",
    "André",
    "Queen Amaya",
    "Angel Kitty",
    "Captain Amelia",
    "Anger",
    "Amphitryon and Alcmene",
    "Anglerfish",
    "Anita Radcliffe",
    "Lord Angstrom",
    "Ankylosaurus",
    "Angus",
    "Animal Council",
    "Annette, Collette, and Danielle",
    "Ant Colony",
    "Antonio Madrigal's Animals",
    "Anxiety",
    "Antony Snootley",
    "Concetta and Pinuccia Aragosta",
    "Apatosaurus",
    "Archie",
    "Aphrodite",
    "Arlo",
    "Apollo (Fantasia)",
    "Arrival Agent",
    "Apollo (Hercules)",
    "Principal Arroyo",
    "Aracuan Bird",
    "Art",
    "Arawn",
    "Astro Blasters Robots",
    "Archaeopteryx",
    "Atlas (Toy Story)",
    "Archdeacon",
    "Atta",
    "Archimedes",
    "AUTO",
    "Ares (Hercules)",
    "Avel",
    "Queen Arianna",
    "Awe",
    "Axel",
    "Armpit Pete",
    "Miles Axlerod",
    "Mr. Arrow",
    "Alec Azam",
    "Artemis",
    "Mr. B",
    "Arthur (Wreck-It Ralph)",
    "Baby (Nona)",
    "Asha",
    "Babyface",
    "Athena",
    "The Badger",
    "Atlanteans",
    "Bailey",
    "Attila",
    "Bambino",
    "Audrey (Home on the Range)",
    "Banana Bread",
    "Audrey Ramirez",
    "Barbie",
    "Aunt Cass",
    "Barbra (Win or Lose)",
    "Aurora",
    "Barrel of Monkeys",
    "Avalonia",
    "Bass",
    "Avalonia Creatures",
    "Battlesaurs",
    "B.E.N.",
    "Becky (Finding Nemo)",
    "Baboons",
    "Ben (Monsters at Work)",
    "Baby Baboon",
    "Carla Benitez",
    "Baby Parasaurolophus",
    "Bensons",
    "Bacchus (Fantasia)",
    "Bernie Kropp",
    "The Backson",
    "Bernie Lumen",
    "Bad-Anon",
    "Francesco Bernoulli",
    "Dr. Badger",
    "Honey Best",
    "Bagheera",
    "Beta and Gamma",
    "Baitmouse",
    "Big Baby",
    "Ballerina",
    "Big D",
    "Balloon",
    "Thaddeus Bile",
    "Baloo",
    "Bill (Finding Nemo)",
    "Baltus Van Tassel",
    "Billy",
    "Bambi",
    "Billy's Toys",
    "Bambi's mother",
    "Billy, Goat, and Gruff",
    "Bandar-log",
    "Bing Bong",
    "Barry and Bob",
    "Bird",
    "Sir Bart",
    "Bird (Dug Days)",
    "Bartholomew",
    "Bird King",
    "Bashful",
    "Birds (For the Birds)",
    "Basil of Baker Street",
    "Bitey White",
    "Baylene",
    "Bizz Leapyear, Buzztron, and Blip Laserfist",
    "Baymax",
    "Blaze Manoukian",
    "Bayou Animals",
    "Blazey",
    "Bazeema",
    "Blenny",
    "The Bear",
    "Argus Blinks",
    "Bearoness Bear",
    "Bloofy",
    "Bears (Bongo)",
    "Blue Umbrella",
    "Beast",
    "The Blueberries",
    "Beaudreaux",
    "Bob Cutlass",
    "Beef Roger Crummchuk",
    "Randall Boggs",
    "The Bees",
    "Bomb Voyage",
    "Boo",
    "Ben Ali Gator",
    "Bookworm",
    "Ben and Lon",
    "Borna",
    "Berlioz",
    "Boss",
    "Bernard (The Rescuers)",
    "Brain Pods",
    "Miss Bianca",
    "Brazilian Helicopter Pilot",
    "Big Hero 6 (team)",
    "Brian Dyson",
    "Big Mama",
    "Brick",
    "Big Nose",
    "Brook Ripple",
    "Big Toot",
    "Bruce",
    "Mr. Big (Zootopia)",
    "Bryce",
    "Bill the Lizard",
    "Bubbha (The Good Dinosaur)",
    "Billie Doe",
    "Buck (The Good Dinosaur)",
    "Billie Robinson",
    "Buddy (Buzz Lightyear attractions)",
    "The Bimbettes",
    "Bullseye",
    "Birds (Beauty and the Beast)",
    "BURN-E",
    "Birds (Cinderella)",
    "Buster (Toy Story)",
    "Black Triangles",
    "Butch (The Good Dinosaur)",
    "Blake, Tom, and Billy",
    "Buttercup",
    "Blobfish (Moana)",
    "Alice Blue Bonnet",
    "Buzz Lightyear (Lightyear)",
    "Blue Fairy",
    "Buzz Lightyear (Star Command)",
    "Bob (Hercules)",
    "C.C. Stump",
    "Chief Bogo",
    "Caleb (Elio)",
    "Bolt",
    "Caligola",
    "Billy Bones (Treasure Planet)",
    "Capitano Briganti",
    "Madame Adelaide Bonfamille",
    "Captain B. McCrea",
    "Bongo the Bear",
    "Captain Suds",
    "The Bookseller",
    "Car-itters",
    "Boreas (Fantasia)",
    "Carl Reineroceros",
    "Boun",
    "Don Carlton",
    "Brachiosaurus",
    "Carole (Win or Lose)",
    "Bread-and-Butterflies",
    "Sally Carrera",
    "Brom Bones",
    "Cave Family",
    "Sheriff Sam Brown",
    "Cecilia (Coco)",
    "Brudus",
    "Centaurs",
    "Bruni",
    "Centaurs (Onward)",
    "Bruno (Cinderella)",
    "Los Chachalacos",
    "Bruno Madrigal",
    "Chairol Burnett",
    "Bruno's Rats",
    "Chalooby",
    "Brutish and Oafish Guards",
    "Charlie (Finding Nemo)",
    "Bruton",
    "Chatter Telephone",
    "Brutus and Nero",
    "Chef Skinner",
    "Cobra Bubbles",
    "Chelsea, Heidi, and Kara",
    "Buck",
    "Chen, Ping, Helen, and Lily",
    "Buck Cluck",
    "Cheryl",
    "Bucket (Hexed)",
    "Chicharrón",
    "Bucky and Pronk Oryx-Antlerson",
    "Chicken-Kev",
    "Bucky the Squirrel",
    "Child Detection Agency",
    "Bud Robinson",
    "Chuck E. Duck",
    "Buford (The Princess and the Frog)",
    "Chuckles the Clown",
    "Bulda",
    "Chum",
    "Bumble",
    "Chunk",
    "Burrito",
    "Ciccio and Guido",
    "Buster (Meet the Robinsons)",
    "Cindy (Bao)",
    "Mr. Busy",
    "Circus Bugs",
    "Butterflies (The Princess and the Frog)",
    "Clan Dingwall",
    "Buzzie, Flaps, Ziggy, and Dizzy",
    "Clan DunBroch",
    "Caledonian Boar",
    "Clan MacGuffin",
    "Sergeant Calhoun",
    "Clan Macintosh",
    "Dr. Calico",
    "Claudia (Partly Cloudy)",
    "Abigail Callaghan",
    "Santa Claus",
    "Mrs. Calloway",
    "Alistair Clawbottom",
    "Camilo Madrigal",
    "The Cleric",
    "Candlehead",
    "Clod",
    "King Candy",
    "Clouds (Partly Cloudy)",
    "Captain (101 Dalmatians)",
    "Cluckers",
    "Captain Crocodile",
    "Coach Dan",
    "Captain Hook",
    "Coach Roberts",
    "Captain Nathaniel Flint",
    "Cobweb",
    "Captain of the Guards",
    "Colette Tatou",
    "Card Soldiers",
    "Colt Bronco",
    "Caribou Stampede",
    "Combat Carl",
    "José Carioca",
    "Commander Burnside",
    "Carl the Robot",
    "Conan",
    "Carlotta",
    "Conner",
    "Carnotaurus",
    "Connie",
    "Casa Madrigal",
    "Construction Foreman Tom",
    "Casey (Make Mine Music)",
    "Construction Supervisor",
    "Casey Junior",
    "Construction Worker Steve",
    "Caspian",
    "Coral",
    "Castle Maids",
    "Corey the Manticore",
    "Caterpillar",
    "Corrections Officer",
    "Cattrick and Kitty Lynxley",
    "Cosmo (Lightyear)",
    "Caucus Race Animals",
    "The Crow",
    "Cauldron Born",
    "Mr. Crummyham",
    "Cave of Wonders",
    "Crush",
    "Centaurettes",
    "Cuddles the Alligator",
    "Curley Baker",
    "Inventco CEO",
    "The Curse Dragon",
    "Ceratosaurus",
    "Cutter",
    "Cerberus",
    "Cyclopes",
    "Cetus",
    "D-FIB",
    "Chaca",
    "Dad (Bao)",
    "Chairmouse",
    "Daffodil",
    "Prince Charming",
    "Daisy (Toy Story)",
    "Charon",
    "Dani (Inside Out 2)",
    "Charybdis",
    "Danny Swervez",
    "Chef Bouche",
    "Dante",
    "Chef Louis",
    "Dante (Elemental)",
    "Chernabog",
    "Darby Steel",
    "Chernabog's Minions",
    "Warp Darkmatter",
    "Cherubs",
    "Darla",
    "Cheshire Cat",
    "Darrell Cartrip",
    "Chi-Fu",
    "Dash Parr",
    "Chicha",
    "David (Monsters, Inc.)",
    "Chicks",
    "Andy Davis",
    "Chief",
    "Molly Davis",
    "Chief Benja",
    "Mrs. Davis",
    "Chief Tui",
    "Day",
    "Chip and Dale",
    "Evelyn Deavor",
    "Chispi",
    "Nelson Deavor",
    "Chloe Cluck",
    "Winston Deavor",
    "Declan",
    "Cinderella's Father",
    "Deep Dark Secret",
    "Cinderella's Mother",
    "Departure Agent",
    "Circus Animals",
    "Despair (Inside Out)",
    "Circus Elephants",
    "Destiny (Finding Dory)",
    "Ethan Clade",
    "Devon (Turning Red)",
    "Jaeger Clade",
    "Dewdrop",
    "Meridian Clade",
    "Dez (Soul)",
    "Searcher Clade",
    "Diane Shark",
    "The Clades",
    "Presto DiGiotagione",
    "Clarinet",
    "Wee Dingwall",
    "Clawhauser",
    "Diplodocus",
    "Clayton",
    "Discarded Fun Meal Toys",
    "Clayton's Men",
    "Disgust",
    "Cleo",
    "Django",
    "Clopin",
    "Doctor (Soul)",
    "Clowns",
    "Dolly",
    "Chicken Little (2005 character)",
    "Dolphina",
    "The Coachman's Assistants",
    "Don Crumlin",
    "The Coachman",
    "Doorman (Elemental)",
    "Coat Rack",
    "Cocoa",
    "Dot",
    "Cody (The Rescuers)",
    "Dr. Nutcase",
    "Cody's Mother",
    "Dragon the Cat",
    "Cogsworth",
    "Drips the Whale",
    "Collie",
    "Ducky and Bunny",
    "Colonel",
    "Dug",
    "Colorful Triangles",
    "Duke Caboom",
    "Compsognathus",
    "Dumpling (Bao)",
    "Condor",
    "Sandy Dunes",
    "Cookie (Atlantis: The Lost Empire)",
    "Durga",
    "Copper",
    "Airman Díaz",
    "Cotton (Zootopia)",
    "Earl (The Good Dinosaur)",
    "Cow (Mickey and the Beanstalk)",
    "Dale Earnhardt Jr.",
    "The Cows (101 Dalmatians)",
    "Eddy Ripple"
  ]
};
